# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AffichageNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AffichageNote(object):
    def setupUi(self, AffichageNote,dicts):
        AffichageNote.setObjectName("AffichageNote")
        AffichageNote.resize(726, 530)
        AffichageNote.setStatusTip("")
        self.tableAffichage = QtWidgets.QTableWidget(AffichageNote)
        self.tableAffichage.setGeometry(QtCore.QRect(0, 130, 1371, 511))
        self.tableAffichage.setStyleSheet("QWidget#widget{\n"
"\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" \n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
" }\n"
"")
        self.tableAffichage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableAffichage.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAffichage.setTabKeyNavigation(True)
        self.tableAffichage.setGridStyle(QtCore.Qt.DashLine)
        self.tableAffichage.setObjectName("tableAffichage")
        self.tableAffichage.setColumnCount(4)
        self.tableAffichage.setRowCount(len(dicts.keys())+1)
        item = QtWidgets.QTableWidgetItem()
        self.tableAffichage.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(3, item)
        self.tableAffichage.horizontalHeader().setCascadingSectionResizes(False)
        self.tableAffichage.horizontalHeader().setDefaultSectionSize(170)
        self.tableAffichage.horizontalHeader().setStretchLastSection(False)
        self.widget = QtWidgets.QWidget(AffichageNote)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 1371, 211))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.AffichageNote_2 = QtWidgets.QLabel(self.widget)
        self.AffichageNote_2.setGeometry(QtCore.QRect(140, 50, 401, 51))
        self.AffichageNote_2.setObjectName("AffichageNote_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 30, 101, 91))
        self.Icon.setObjectName("Icon")
        self.widget.raise_()
        self.tableAffichage.raise_()
        self.loadData(dicts)
        self.retranslateUi(AffichageNote)
        QtCore.QMetaObject.connectSlotsByName(AffichageNote)

    def retranslateUi(self, AffichageNote):
        _translate = QtCore.QCoreApplication.translate
        AffichageNote.setWindowTitle(_translate("AffichageNote", "Form"))
        item = self.tableAffichage.verticalHeaderItem(0)
        item.setText(_translate("AffichageNote", "1"))
        item = self.tableAffichage.horizontalHeaderItem(0)
        item.setText(_translate("AffichageNote", "Numeros d\'inscriptions"))
        item = self.tableAffichage.horizontalHeaderItem(1)
        item.setText(_translate("AffichageNote", "Code"))
        item = self.tableAffichage.horizontalHeaderItem(2)
        item.setText(_translate("AffichageNote", "Note DS"))
        item = self.tableAffichage.horizontalHeaderItem(3)
        item.setText(_translate("AffichageNote", "Note Examen"))
        self.AffichageNote_2.setText(_translate("AffichageNote", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">Affichage Note</span></p></body></html>"))
        self.Icon.setText(_translate("AffichageNote", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
    def loadData (self,dicts):
        row=0
        for keys in dicts :
            self.tableAffichage.setItem(row,0,QtWidgets.QTableWidgetItem(str(keys[0])))
            self.tableAffichage.setItem(row,1,QtWidgets.QTableWidgetItem(str(keys[1])))
            self.tableAffichage.setItem(row,2,QtWidgets.QTableWidgetItem(str(dicts[keys][0])))
            self.tableAffichage.setItem(row,3,QtWidgets.QTableWidgetItem(str(dicts[keys][1])))
        
            row=row+1
            
    
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AffichageNote = QtWidgets.QWidget()
    ui = Ui_AffichageNote()
    ui.setupUi(AffichageNote,dicts)
    AffichageNote.show()
    sys.exit(app.exec_())
