# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Affichage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AffichageEtudiant(object):
    def setupUi(self, AffichageEtudiant,Dicts,ch="Affichage Etudiants"):
        AffichageEtudiant.setObjectName("AffichageEtudiant")
        AffichageEtudiant.resize(1354, 632)
        AffichageEtudiant.setStatusTip("")
        self.tableAffichage = QtWidgets.QTableWidget(AffichageEtudiant)
        self.tableAffichage.setGeometry(QtCore.QRect(0, 130, 1371, 511))
        self.tableAffichage.setStyleSheet("QWidget#widget{\n"
"\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" \n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
" }\n"
"")
        self.tableAffichage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableAffichage.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAffichage.setTabKeyNavigation(True)
        self.tableAffichage.setGridStyle(QtCore.Qt.DashLine)
        self.tableAffichage.setObjectName("tableAffichage")
        self.tableAffichage.setColumnCount(9)
        self.tableAffichage.setRowCount(len(Dicts.keys())+1)
        item = QtWidgets.QTableWidgetItem()
        self.tableAffichage.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        
        self.tableAffichage.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(8, item)
        self.tableAffichage.horizontalHeader().setCascadingSectionResizes(False)
        self.tableAffichage.horizontalHeader().setDefaultSectionSize(148)
        self.tableAffichage.horizontalHeader().setStretchLastSection(False)
        self.IconEtudiant = QtWidgets.QLabel(AffichageEtudiant)
        self.IconEtudiant.setGeometry(QtCore.QRect(40, 20, 101, 101))
        self.IconEtudiant.setObjectName("IconEtudiant")
        self.widget = QtWidgets.QWidget(AffichageEtudiant)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 1371, 211))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.AffichageEtudiants = QtWidgets.QLabel(self.widget)
        self.AffichageEtudiants.setGeometry(QtCore.QRect(170, 45, 900, 51))
        self.AffichageEtudiants.setObjectName("AffichageEtudiants")
        self.widget.raise_()
        self.IconEtudiant.raise_()
        self.tableAffichage.raise_()
        self.loadData(Dicts)
        self.retranslateUi(AffichageEtudiant,ch)
        QtCore.QMetaObject.connectSlotsByName(AffichageEtudiant)

    def retranslateUi(self, AffichageEtudiant,ch):
        _translate = QtCore.QCoreApplication.translate
        AffichageEtudiant.setWindowTitle(_translate("AffichageEtudiant", "Affichage Etudiant"))
        item = self.tableAffichage.verticalHeaderItem(0)
        item.setText(_translate("AffichageEtudiant", "1"))
        item = self.tableAffichage.horizontalHeaderItem(0)
        item.setText(_translate("AffichageEtudiant", "Numeros d\'inscriptions"))
        item = self.tableAffichage.horizontalHeaderItem(1)
        item.setText(_translate("AffichageEtudiant", "Noms"))
        item = self.tableAffichage.horizontalHeaderItem(2)
        item.setText(_translate("AffichageEtudiant", "Prenoms"))
        item = self.tableAffichage.horizontalHeaderItem(3)
        item.setText(_translate("AffichageEtudiant", "Dates de Naissances"))
        item = self.tableAffichage.horizontalHeaderItem(4)
        item.setText(_translate("AffichageEtudiant", "Adresses"))
        item = self.tableAffichage.horizontalHeaderItem(5)
        item.setText(_translate("AffichageEtudiant", "Mails"))
        item = self.tableAffichage.horizontalHeaderItem(6)
        item.setText(_translate("AffichageEtudiant", "Telephones"))
        item = self.tableAffichage.horizontalHeaderItem(7)
        item.setText(_translate("AffichageEtudiant", "Sections"))
        item = self.tableAffichage.horizontalHeaderItem(8)
        item.setText(_translate("AffichageEtudiant", "Niveaux"))
        self.IconEtudiant.setText(_translate("AffichageEtudiant", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.AffichageEtudiants.setText(_translate("AffichageEtudiant", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">"+ch+"</span></p></body></html>"))


    def loadData (self,Dicts):
        row=0
        for keys in Dicts :
            self.tableAffichage.setItem(row,0,QtWidgets.QTableWidgetItem(str(keys)))
            self.tableAffichage.setItem(row,1,QtWidgets.QTableWidgetItem(str(Dicts[keys][0])))
            self.tableAffichage.setItem(row,2,QtWidgets.QTableWidgetItem(str(Dicts[keys][1])))
            self.tableAffichage.setItem(row,3,QtWidgets.QTableWidgetItem(str(Dicts[keys][2])))
            self.tableAffichage.setItem(row,4,QtWidgets.QTableWidgetItem(str(Dicts[keys][3])))
            self.tableAffichage.setItem(row,5,QtWidgets.QTableWidgetItem(str(Dicts[keys][4])))
            self.tableAffichage.setItem(row,6,QtWidgets.QTableWidgetItem(str(Dicts[keys][5])))
            self.tableAffichage.setItem(row,7,QtWidgets.QTableWidgetItem(str(Dicts[keys][6])))            
            self.tableAffichage.setItem(row,8,QtWidgets.QTableWidgetItem(str(Dicts[keys][7])))
            row=row+1
            
import icons_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    AffichageEtudiant = QtWidgets.QWidget()
    ui = Ui_AffichageEtudiant()
    Dicts={}
    ui.setupUi(AffichageEtudiant,Dicts)
    AffichageEtudiant.show()
    sys.exit(app.exec_())
