# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AffichageMatiere.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AffichageMatiere(object):
    def setupUi(self, AffichageMatiere,Dicts):
        AffichageMatiere.setObjectName("AffichageMatiere")
        AffichageMatiere.resize(905, 605)
        AffichageMatiere.setStatusTip("")
        self.tableAffichage = QtWidgets.QTableWidget(AffichageMatiere)
        self.tableAffichage.setGeometry(QtCore.QRect(0, 130, 1371, 511))
        self.tableAffichage.setStyleSheet("QWidget#widget{\n"
"\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" \n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
" }\n"
"")
        self.tableAffichage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableAffichage.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAffichage.setTabKeyNavigation(True)
        self.tableAffichage.setGridStyle(QtCore.Qt.DashLine)
        self.tableAffichage.setObjectName("tableAffichage")
        self.tableAffichage.setColumnCount(5)
        self.tableAffichage.setRowCount(len(Dicts.keys())+1)
        item = QtWidgets.QTableWidgetItem()
        self.tableAffichage.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableAffichage.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAffichage.setHorizontalHeaderItem(4, item)
        self.tableAffichage.horizontalHeader().setCascadingSectionResizes(False)
        self.tableAffichage.horizontalHeader().setDefaultSectionSize(170)
        self.tableAffichage.horizontalHeader().setStretchLastSection(False)
        self.widget = QtWidgets.QWidget(AffichageMatiere)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 1371, 211))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.AffichageMatieres = QtWidgets.QLabel(self.widget)
        self.AffichageMatieres.setGeometry(QtCore.QRect(140, 50, 401, 51))
        self.AffichageMatieres.setObjectName("AffichageMatieres")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 91))
        self.label.setObjectName("label")
        self.widget.raise_()
        self.tableAffichage.raise_()

        self.retranslateUi(AffichageMatiere)
        QtCore.QMetaObject.connectSlotsByName(AffichageMatiere)
        self.loadData(Dicts)
    def retranslateUi(self, AffichageMatiere):
        _translate = QtCore.QCoreApplication.translate
        AffichageMatiere.setWindowTitle(_translate("AffichageMatiere", "Form"))
        item = self.tableAffichage.verticalHeaderItem(0)
        item.setText(_translate("AffichageMatiere", "1"))
        item = self.tableAffichage.horizontalHeaderItem(0)
        item.setText(_translate("AffichageMatiere", "Code"))
        item = self.tableAffichage.horizontalHeaderItem(1)
        item.setText(_translate("AffichageMatiere", "Designation"))
        item = self.tableAffichage.horizontalHeaderItem(2)
        item.setText(_translate("AffichageMatiere", "Section"))
        item = self.tableAffichage.horizontalHeaderItem(3)
        item.setText(_translate("AffichageMatiere", "Coefficient"))
        item = self.tableAffichage.horizontalHeaderItem(4)
        item.setText(_translate("AffichageMatiere", "Semestre"))
        self.AffichageMatieres.setText(_translate("AffichageMatiere", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">Affichage Matiere</span></p></body></html>"))
        self.label.setText(_translate("AffichageMatiere", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
    def loadData (self,Dicts):
        row=0
        for keys in Dicts :
            self.tableAffichage.setItem(row,0,QtWidgets.QTableWidgetItem(str(keys)))
            self.tableAffichage.setItem(row,1,QtWidgets.QTableWidgetItem(str(Dicts[keys][0])))
            self.tableAffichage.setItem(row,2,QtWidgets.QTableWidgetItem(str(Dicts[keys][1])))
            self.tableAffichage.setItem(row,3,QtWidgets.QTableWidgetItem(str(Dicts[keys][2])))
            self.tableAffichage.setItem(row,4,QtWidgets.QTableWidgetItem(str(Dicts[keys][3])))        
            
            row=row+1

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AffichageMatiere = QtWidgets.QWidget()
    ui = Ui_AffichageMatiere()
    Dicts={}
    ui.setupUi(AffichageMatiere,Dicts)
    AffichageMatiere.show()
    sys.exit(app.exec_())
