# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajouterNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import code
from PyQt5 import QtCore, QtGui, QtWidgets
import Note as NT
import Etudiant as ET
import Matiere as Mat


class Ui_AjoutNote(object):
    def setupUi(self, AjoutNote):
        AjoutNote.setObjectName("AjoutNote")
        AjoutNote.resize(582, 521)
        self.centralwidget = QtWidgets.QWidget(AjoutNote)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, -10, 701, 791))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")

        self.NumInscrit = QtWidgets.QLineEdit(self.widget)
        self.NumInscrit.setGeometry(QtCore.QRect(220, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit.setFont(font)
        self.NumInscrit.setObjectName("NumInscrit")

        self.NumInscrit_2 = QtWidgets.QLabel(self.widget)
        self.NumInscrit_2.setGeometry(QtCore.QRect(220, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit_2.setFont(font)
        self.NumInscrit_2.setObjectName("NumInscrit_2")

        self.Code = QtWidgets.QLineEdit(self.widget)
        self.Code.setGeometry(QtCore.QRect(220, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.NoteEx = QtWidgets.QLineEdit(self.widget)
        self.NoteEx.setGeometry(QtCore.QRect(220, 250, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteEx.setFont(font)
        self.NoteEx.setObjectName("NoteEx")
        self.NoteDs = QtWidgets.QLineEdit(self.widget)
        self.NoteDs.setGeometry(QtCore.QRect(220, 320, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteDs.setFont(font)
        self.NoteDs.setObjectName("NoteDs")
        self.pushButtonAjout = QtWidgets.QPushButton(self.widget)
        self.pushButtonAjout.setGeometry(QtCore.QRect(390, 380, 75, 23))
        self.pushButtonAjout.setObjectName("pushButtonAjout")
        self.NoteEx_2 = QtWidgets.QLabel(self.widget)
        self.NoteEx_2.setGeometry(QtCore.QRect(220, 220, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteEx_2.setFont(font)
        self.NoteEx_2.setObjectName("NoteEx_2")
        self.NoteDs_2 = QtWidgets.QLabel(self.widget)
        self.NoteDs_2.setGeometry(QtCore.QRect(220, 290, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteDs_2.setFont(font)
        self.NoteDs_2.setObjectName("NoteDs_2")
        self.NumInscrit_2 = QtWidgets.QLabel(self.widget)
        self.NumInscrit_2.setGeometry(QtCore.QRect(220, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit_2.setFont(font)
        self.NumInscrit_2.setObjectName("NumInscrit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(200, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonAjout.clicked.connect(self.getInfos)

        self.AjoutInvalide = QtWidgets.QLabel(self.widget)
        self.AjoutInvalide.setGeometry(QtCore.QRect(260, 40, 261, 31))
        self.AjoutInvalide.setObjectName("AjoutInvalide")
        self.AjoutInvalide.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 80, 111, 151))
        self.label.setObjectName("label")
        self.NumInscrit = QtWidgets.QLineEdit(self.widget)
        self.NumInscrit.setGeometry(QtCore.QRect(220, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit.setFont(font)
        self.NumInscrit.setObjectName("NumInscrit")
        self.Code_2 = QtWidgets.QLabel(self.widget)
        self.Code_2.setGeometry(QtCore.QRect(220, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code_2.setFont(font)
        self.Code_2.setObjectName("Code_2")
        AjoutNote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AjoutNote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        AjoutNote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AjoutNote)
        self.statusbar.setObjectName("statusbar")
        AjoutNote.setStatusBar(self.statusbar)

        self.retranslateUi(AjoutNote)
        QtCore.QMetaObject.connectSlotsByName(AjoutNote)

    def retranslateUi(self, AjoutNote):
        _translate = QtCore.QCoreApplication.translate
        AjoutNote.setWindowTitle(_translate("AjoutNote", "Ajouter Note"))

        self.pushButtonAjout.setText(_translate("AjoutNote", "Ajouter"))
        self.NoteEx_2.setText(_translate("AjoutNote", "<html><head/><body><p><span style=\" color:#ffffff;\">Note d\'examen</span></p></body></html>"))
        self.NoteDs_2.setText(_translate("AjoutNote", "<html><head/><body><p><span style=\" color:#ffffff;\">Note DS</span></p></body></html>"))
        self.NumInscrit_2.setText(_translate("AjoutNote", "<html><head/><body><p><span style=\" color:#ffffff;\">Numero d\'inscription</span></p></body></html>"))
        self.pushButton.setText(_translate("AjoutNote", "Cancel"))
        self.AjoutInvalide.setText(_translate("AjoutNote", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Ajout invalide</span></p></body></html>"))
        self.label.setText(_translate("AjoutNote", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        
        self.Code_2.setText(_translate("AjoutNote", "<html><head/><body><p><span style=\" color:#ffffff;\">Code</span></p></body></html>"))
    def getInfos(self):
        NumInscrit=self.NumInscrit.text()
        Code=self.Code.text()
        NoteEX=self.NoteEx.text()
        NoteDS=self.NoteDs.text() 
        if ((NumInscrit in ET.Etudiants.keys()) and (Code in Mat.Matieres.keys()) and(not (NumInscrit,Code)in NT.Notes) and ((ET.Etudiants[NumInscrit][6]==Mat.Matieres[Code][1])) and (NT.SaisieNote(NoteEX)) and (NT.SaisieNote(NoteDS))):  
            NT.Notes.update({(NumInscrit,Code):[NoteDS,NoteEX]})
            self.AjoutInvalide.setHidden(True)
            
        else :
            self.AjoutInvalide.setHidden(False)   
        print(NT.Notes)

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AjoutNote = QtWidgets.QMainWindow()
    ui = Ui_AjoutNote()
    ui.setupUi(AjoutNote)
    AjoutNote.show()
    sys.exit(app.exec_())