# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajouterMatiere.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Matiere as Mat


class Ui_AjoutMatiere(object):
    def setupUi(self, AjoutMatiere):
        AjoutMatiere.setObjectName("AjoutMatiere")
        AjoutMatiere.resize(601, 560)
        self.centralwidget = QtWidgets.QWidget(AjoutMatiere)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-20, -20, 701, 791))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Code = QtWidgets.QLineEdit(self.widget)
        self.Code.setGeometry(QtCore.QRect(220, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.Code_2 = QtWidgets.QLabel(self.widget)
        self.Code_2.setGeometry(QtCore.QRect(220, 80, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code_2.setFont(font)
        self.Code_2.setObjectName("Code_2")
         
        self.Designation = QtWidgets.QLineEdit(self.widget)
        self.Designation.setGeometry(QtCore.QRect(220, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Designation.setFont(font)
        self.Designation.setObjectName("Designation")
        self.Section = QtWidgets.QLineEdit(self.widget)
        self.Section.setGeometry(QtCore.QRect(220, 250, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section.setFont(font)
        self.Section.setObjectName("Section")
        self.Coefficient = QtWidgets.QLineEdit(self.widget)
        self.Coefficient.setGeometry(QtCore.QRect(220, 320, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Coefficient.setFont(font)
        self.Coefficient.setObjectName("Coefficient")
        self.Semestre = QtWidgets.QLineEdit(self.widget)
        self.Semestre.setGeometry(QtCore.QRect(220, 390, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Semestre.setFont(font)
        self.Semestre.setObjectName("Semestre")
        self.pushButtonAjout = QtWidgets.QPushButton(self.widget)
        self.pushButtonAjout.setGeometry(QtCore.QRect(390, 440, 75, 23))
        self.pushButtonAjout.setObjectName("pushButtonAjout")
        self.pushButtonAjout.clicked.connect(self.getInfos)
        self.Section_2 = QtWidgets.QLabel(self.widget)
        self.Section_2.setGeometry(QtCore.QRect(220, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section_2.setFont(font)
        self.Section_2.setObjectName("Section_2")
        self.Coefficient_2 = QtWidgets.QLabel(self.widget)
        self.Coefficient_2.setGeometry(QtCore.QRect(220, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Coefficient_2.setFont(font)
        self.Coefficient_2.setObjectName("Coefficient_2")
        self.Semestre_2 = QtWidgets.QLabel(self.widget)
        self.Semestre_2.setGeometry(QtCore.QRect(220, 360, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Semestre_2.setFont(font)
        self.Semestre_2.setObjectName("Semestre_2")
        self.Designation_2 = QtWidgets.QLabel(self.widget)
        self.Designation_2.setGeometry(QtCore.QRect(220, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Designation_2.setFont(font)
        self.Designation_2.setObjectName("Designation_2")
   
        self.AjoutInvalide = QtWidgets.QLabel(self.widget)
        self.AjoutInvalide.setGeometry(QtCore.QRect(260, 40, 261, 31))
        self.AjoutInvalide.setObjectName("AjoutInvalide")
        self.AjoutInvalide.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 130, 111, 151))
        self.label.setObjectName("label")
        AjoutMatiere.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AjoutMatiere)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.menubar.setObjectName("menubar")
        AjoutMatiere.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AjoutMatiere)
        self.statusbar.setObjectName("statusbar")
        AjoutMatiere.setStatusBar(self.statusbar)

        self.retranslateUi(AjoutMatiere)
        QtCore.QMetaObject.connectSlotsByName(AjoutMatiere)

    def retranslateUi(self, AjoutMatiere):
        _translate = QtCore.QCoreApplication.translate
        AjoutMatiere.setWindowTitle(_translate("AjoutMatiere", "Ajouter Matiere"))

        self.pushButtonAjout.setText(_translate("AjoutMatiere", "Ajouter"))
        self.Section_2.setText(_translate("AjoutMatiere", "<html><head/><body><p><span style=\" color:#ffffff;\">Section</span></p></body></html>"))
        self.Coefficient_2.setText(_translate("AjoutMatiere", "<html><head/><body><p><span style=\" color:#ffffff;\">Coefficient</span></p></body></html>"))
        self.Semestre_2.setText(_translate("AjoutMatiere", "<html><head/><body><p><span style=\" color:#ffffff;\">Semestre</span></p></body></html>"))
        self.Designation_2.setText(_translate("AjoutMatiere", "<html><head/><body><p><span style=\" color:#ffffff;\">Designation</span></p></body></html>"))
       
        self.AjoutInvalide.setText(_translate("AjoutMatiere", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Ajout invalide</span></p></body></html>"))
        self.label.setText(_translate("AjoutMatiere", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))

        self.Code_2.setText(_translate("AjoutMatiere", "<html><head/><body><p><span style=\" color:#ffffff;\">Code</span></p></body></html>"))
    def getInfos(self):
        Code=self.Code.text()
        Designation=self.Designation.text()
        Section=self.Section.text()
        Coefficient=self.Coefficient.text()
        Semestre=self.Semestre.text()
        
        if (Mat.SaisieCode(Code) and (Code not in Mat.Matieres) and Mat.SaisieDesignation(Designation) and Mat.SaisieCoefficient(Coefficient) and Mat.SaisieSemestre(Semestre)):
            Mat.Matieres.update({Code:[Designation,Section,Coefficient,(Semestre).upper()]})
            self.AjoutInvalide.setHidden(True)
        else :
            
            self.AjoutInvalide.setHidden(False)
        print (Mat.Matieres)
           
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AjoutMatiere = QtWidgets.QMainWindow()
    ui = Ui_AjoutMatiere()
    ui.setupUi(AjoutMatiere)
    AjoutMatiere.show()
    sys.exit(app.exec_())
