# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnregistrementET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import Etudiant as ET
from Exporting_Etudiant import *
import tkinter as tk
from tkinter import filedialog



class Ui_EnregistrementEtudiant(object):
    def setupUi(self, EnregistrementEtudiant,ch=""):
        EnregistrementEtudiant.setObjectName("EnregistrementEtudiant")
        EnregistrementEtudiant.resize(585, 466)
        self.centralwidget = QtWidgets.QWidget(EnregistrementEtudiant)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 40, 101, 101))
        self.Icon.setObjectName("Icon")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 50, 461, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(390, 200, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.NomFichier = QtWidgets.QLineEdit(self.widget)
        self.NomFichier.setGeometry(QtCore.QRect(150, 199, 221, 21))
        self.NomFichier.setObjectName("NomFichie")
        self.ButtonEnregistrer = QtWidgets.QPushButton(self.widget)
        self.ButtonEnregistrer.setGeometry(QtCore.QRect(404, 300, 101, 31))
        self.ButtonEnregistrer.setStyleSheet("")
        self.ButtonEnregistrer.setObjectName("ButtonEnregistrer")
        self.ButtonEnregistrer.clicked.connect(lambda:self.Enregistrer(ch))
        self.TaperLeNom = QtWidgets.QLabel(self.widget)
        self.TaperLeNom.setGeometry(QtCore.QRect(150, 160, 221, 31))
        self.TaperLeNom.setObjectName("TaperLeNom")
        EnregistrementEtudiant.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(EnregistrementEtudiant)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        EnregistrementEtudiant.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EnregistrementEtudiant)
        self.statusbar.setObjectName("statusbar")
        EnregistrementEtudiant.setStatusBar(self.statusbar)
        self.retranslateUi(EnregistrementEtudiant)
        QtCore.QMetaObject.connectSlotsByName(EnregistrementEtudiant)

    def retranslateUi(self, EnregistrementEtudiant):
        _translate = QtCore.QCoreApplication.translate
        EnregistrementEtudiant.setWindowTitle(_translate("EnregistrementEtudiant", "Enregistrement Etudiant"))
        self.Icon.setText(_translate("EnregistrementEtudiant", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.label.setText(_translate("EnregistrementEtudiant", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Enregistrement de tableau etudiant</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("EnregistrementEtudiant", ".csv"))
        self.comboBox.setItemText(1, _translate("EnregistrementEtudiant", ".txt"))
        self.ButtonEnregistrer.setText(_translate("EnregistrementEtudiant", "Enregistrer"))
        self.TaperLeNom.setText(_translate("EnregistrementEtudiant", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Taper le nom du fichier</span></p></body></html>"))

    
    def SuccesssMsg (self):
        msg=QMessageBox ()
        msg.setWindowTitle ("Enregistrement valider")
        msg.setText("Le tableau est enregistré")
        msg.setStandardButtons(QMessageBox.Ok)
        x=msg.exec_()
    def FailedMsg (self):
        msg=QMessageBox ()
        msg.setWindowTitle ("Enregistrement echoué")
        msg.setText("Il faut entrer un nom valide !")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.setIcon(QMessageBox.Critical)
        msg.setDetailedText("Impossible d'enregistrer le fichier. Essayez l'une des opérations suivantes : \n-Vérifiez que le nom de fichier ne contient aucun des caractères suivants : < >  ? [ ] : | *. \n-Vérifiez que le nom du fichier/chemin ne contient pas plus de 218 caractères.")
        x=msg.exec_()
    
    def Enregistrer (self,ch):
        NomFichier=self.NomFichier.text()
        type = self.comboBox.currentText()
        print(type)
        if ch!="":
            EnregistrerTXT(ET.Etudiants, "Etudiants")

        if (NomFichierValide(NomFichier)):
            if (type ==".txt"):
                EnregistrerTXT(ET.Etudiants,NomFichier)
            else:
                EnregistrerCSV(ET.Etudiants,NomFichier)

            root = tk.Tk()
            root.withdraw()
            filename = filedialog.asksaveasfilename(initialdir='/', title='Save as File', filetypes=(
            ('Text Files', '*.txt'), ('Excel Files', '*.csv'), ('All Files', '*.*')))
            textContent = "I'm the text in the file"
            myfile = open(filename, "w+")
            myfile.write("Hey")



            self.SuccesssMsg()
        else: 
            self.FailedMsg()


import icons_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnregistrementEtudiant = QtWidgets.QMainWindow()
    ui = Ui_EnregistrementEtudiant()
    ui.setupUi(EnregistrementEtudiant)
    EnregistrementEtudiant.show()
    sys.exit(app.exec_())
