# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnregistrementET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import Matiere as Mat
from Exporting_Matiere import *


class Ui_EnregistrementMatiere(object):
    def setupUi(self, EnregistrementMatiere):
        EnregistrementMatiere.setObjectName("EnregistrementMatiere")
        EnregistrementMatiere.resize(585, 466)
        self.centralwidget = QtWidgets.QWidget(EnregistrementMatiere)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 40, 101, 101))
        self.Icon.setObjectName("Icon")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 50, 461, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(390, 200, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.NomFichier = QtWidgets.QLineEdit(self.widget)
        self.NomFichier.setGeometry(QtCore.QRect(150, 199, 221, 21))
        self.NomFichier.setObjectName("NomFichie")
        self.ButtonEnregistrer = QtWidgets.QPushButton(self.widget)
        self.ButtonEnregistrer.setGeometry(QtCore.QRect(404, 300, 101, 31))
        self.ButtonEnregistrer.setStyleSheet("")
        self.ButtonEnregistrer.setObjectName("ButtonEnregistrer")
        self.ButtonEnregistrer.clicked.connect(lambda:self.Enregistrer())
        self.TaperLeNom = QtWidgets.QLabel(self.widget)
        self.TaperLeNom.setGeometry(QtCore.QRect(150, 160, 221, 31))
        self.TaperLeNom.setObjectName("TaperLeNom")
        EnregistrementMatiere.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(EnregistrementMatiere)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        EnregistrementMatiere.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EnregistrementMatiere)
        self.statusbar.setObjectName("statusbar")
        EnregistrementMatiere.setStatusBar(self.statusbar)
        self.retranslateUi(EnregistrementMatiere)
        QtCore.QMetaObject.connectSlotsByName(EnregistrementMatiere)

    def retranslateUi(self, EnregistrementMatiere):
        _translate = QtCore.QCoreApplication.translate
        EnregistrementMatiere.setWindowTitle(_translate("EnregistrementMatiere", "Enregistrement Matiere"))
        self.Icon.setText(_translate("EnregistrementMatiere", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
        self.label.setText(_translate("EnregistrementMatiere", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Enregistrement de tableau Matiere</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("EnregistrementMatiere", ".csv"))
        self.comboBox.setItemText(1, _translate("EnregistrementMatiere", ".txt"))
        self.ButtonEnregistrer.setText(_translate("EnregistrementMatiere", "Enregistrer"))
        self.TaperLeNom.setText(_translate("EnregistrementMatiere", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Taper le nom du fichier</span></p></body></html>"))

    
    def SuccesssMsg (self):
        msg=QMessageBox ()
        msg.setWindowTitle ("Enregistrement valider")
        msg.setText("Le tableau est enregistrer")
        msg.setStandardButtons(QMessageBox.Ok)
        x=msg.exec_()
    def FailedMsg (self):
        msg=QMessageBox ()
        msg.setWindowTitle ("Enregistrement echoué")
        msg.setText("Il faut entrer un nom valide !")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.setIcon(QMessageBox.Critical)
        msg.setDetailedText("Impossible d'enregistrer le fichier. Essayez l'une des opérations suivantes : \n-Vérifiez que le nom de fichier ne contient aucun des caractères suivants : < >  ? [ ] : | *. \n-Vérifiez que le nom du fichier/chemin ne contient pas plus de 218 caractères.")
        x=msg.exec_()
    
    def Enregistrer (self):
        NomFichier=self.NomFichier.text()
        type = self.comboBox.currentText()
        print(type)
        if (NomFichierValide(NomFichier)):
            if (type ==".txt"):
                EnregistrerTXT(Mat.Matieres,NomFichier)
            else:
                EnregistrerCSV(Mat.Matieres,NomFichier)
            self.SuccesssMsg()
        else: 
            self.FailedMsg()


import icons_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnregistrementMatiere = QtWidgets.QMainWindow()
    ui = Ui_EnregistrementMatiere()
    ui.setupUi(EnregistrementMatiere)
    EnregistrementMatiere.show()
    sys.exit(app.exec_())
