# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from EnregistrementMat import Ui_EnregistrementMatiere
from ajouterEtudiant import Ui_AjoutEtudiant
from ajouterMatiere import Ui_AjoutMatiere
from SupEtudiantNumInscrit import Ui_SupEtudiantNumInscrit
from SupEtudiantSection import Ui_SupEtudiantSection
from SupEtudiantNiveau import Ui_SupEtudiantNiveau
from AffichageEtudiant import Ui_AffichageEtudiant
from AffichageMatiere import Ui_AffichageMatiere
from AffichageNote import Ui_AffichageNote
from SuppSectionNivET import Ui_SuppressionSection_Niveau
from ModNumTelET import Ui_ModNumTelET
from ModMailET import Ui_ModMailET
from ModAdresseET import Ui_ModAdresseET
from SupMatiere import Ui_SupMatiere
from ModDesignationMat import Ui_ModDesignationMat
from ModCoefficientMat import Ui_ModCoefficientMat
from RechercheNumInscritET import Ui_RechNumInscritET
from RechSectionET import Ui_RechSectionET
from RechNiveauET import Ui_RechNiveauET
from EnregistrementET import Ui_EnregistrementEtudiant
from EnregistrementMat import Ui_EnregistrementMatiere
from EnregistrementNT import Ui_EnregistrementNote
from RecuperationET import Ui_RecupererationEtudiant
from RecuperationMat import Ui_RecupererationMatiere
from RecuperationNT import Ui_RecupererationNote
from RechCodeMat import Ui_RechCodeMat
from RechSectionMat import Ui_RechSectionMat
from ajouterNote import Ui_AjoutNote
from SupNote import Ui_SupNote
from ModNote import Ui_ModNote
from RechNumInscritNT import Ui_RechNumInscritNT
from RechSectionNiveauET import Ui_RechSectionNiveauET
from RechSectionNiveauNT import Ui_RechSectionNiveauNT
from RechSectionSemestreMat import Ui_RechSectionSemestreMat
from RechNumInscritSemestreNT import Ui_RechNumInscritSemestreNT
from SaisieNumInscrit import Ui_SaisieNumInscritET
from SaisieNumInscritSemestre import Ui_RechNumInscritSemestre
from EtudiantAdmisSection import Ui_EtudiantAdmisSection
from AffichageResultat import Ui_AffichageResultat
from MoyenneSection import Ui_MoyenneSection

import os
import Exporting_Etudiant as EXET
import Exporting_Matiere as EXMat
import Exporting_Note as EXNT

import Note as NT
import Etudiant as ET
import Matiere as Mat

import icons_rc


class Ui_MainWindow(object):

    def open(self, Ui):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui()
        self.ui.setupUi(self.window)
        self.window.show()

    def openArg(self, x, Ui):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui()
        self.ui.setupUi(self.window, x)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.widget.setStyleSheet("QWidget#widget{\n"
                                  "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
                                  " }")
        self.widget.setObjectName("widget")

        self.IconEtudiant = QtWidgets.QLabel(self.widget)
        self.IconEtudiant.setGeometry(QtCore.QRect(140, 110, 101, 101))
        self.IconEtudiant.setObjectName("IconEtudiant")
        self.IconNote = QtWidgets.QLabel(self.widget)
        self.IconNote.setGeometry(QtCore.QRect(140, 410, 101, 111))
        self.IconNote.setObjectName("IconNote")
        self.IconMatiere = QtWidgets.QLabel(self.widget)
        self.IconMatiere.setGeometry(QtCore.QRect(140, 260, 91, 91))
        self.IconMatiere.setObjectName("IconMatiere")
        self.ButtonAffichageEtudiants = QtWidgets.QPushButton(self.widget)
        self.ButtonAffichageEtudiants.setGeometry(QtCore.QRect(120, 110, 731, 91))

        self.ButtonAffichageEtudiants.clicked.connect(lambda: self.openArg(ET.Etudiants, Ui_AffichageEtudiant))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ButtonAffichageEtudiants.setFont(font)
        self.ButtonAffichageEtudiants.setAutoFillBackground(False)
        self.ButtonAffichageEtudiants.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                                    "color: rgb(255, 255, 255);\n"
                                                    "")
        self.ButtonAffichageEtudiants.setFlat(True)
        self.ButtonAffichageEtudiants.setObjectName("ButtonAffichageEtudiants")

        self.AffichageMatiere = QtWidgets.QPushButton(self.widget)
        self.AffichageMatiere.setGeometry(QtCore.QRect(130, 250, 731, 101))
        self.AffichageMatiere.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "")
        self.AffichageMatiere.setFlat(True)
        self.AffichageMatiere.setObjectName("AffichageMatiere")

        self.AffichageMatiere.clicked.connect(lambda: self.openArg(Mat.Matieres, Ui_AffichageMatiere))
        self.AffichageNotes = QtWidgets.QPushButton(self.widget)
        self.AffichageNotes.setGeometry(QtCore.QRect(130, 400, 711, 101))
        self.AffichageNotes.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "")
        self.AffichageNotes.setAutoDefault(False)
        self.AffichageNotes.setDefault(False)
        self.AffichageNotes.setFlat(True)
        self.AffichageNotes.setObjectName("AffichageNotes")
        self.AffichageNotes.clicked.connect(lambda: self.openArg(NT.Notes, Ui_AffichageNote))
        self.CreatedBy = QtWidgets.QLabel(self.widget)
        self.CreatedBy.setGeometry(QtCore.QRect(1110, 680, 251, 20))
        self.CreatedBy.setStyleSheet("color:rgb(255, 255, 255)")
        self.CreatedBy.setObjectName("CreatedBy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEnregistrer = QtWidgets.QMenu(self.menufile)
        self.menuEnregistrer.setObjectName("menuEnregistrer")
        self.menuEnregistrerSous = QtWidgets.QMenu(self.menufile)
        self.menuEnregistrerSous.setObjectName("menuEnregistrerSous")
        self.menuRecuperer = QtWidgets.QMenu(self.menufile)
        self.menuRecuperer.setObjectName("menuRecuperer")
        self.menuRecupererFichier = QtWidgets.QMenu(self.menufile)
        self.menuRecupererFichier.setObjectName("menuRecupererFichier")
        self.menuEtudiant = QtWidgets.QMenu(self.menubar)
        self.menuEtudiant.setObjectName("menuEtudiant")
        self.menuMiseaJourET = QtWidgets.QMenu(self.menuEtudiant)
        self.menuMiseaJourET.setObjectName("menuMiseaJourET")
        self.menuSupprimerET = QtWidgets.QMenu(self.menuMiseaJourET)
        self.menuSupprimerET.setObjectName("menuSupprimerET")
        self.menuModifierET = QtWidgets.QMenu(self.menuMiseaJourET)
        self.menuModifierET.setObjectName("menuModifierET")
        self.menuAffichageRechercheET = QtWidgets.QMenu(self.menuEtudiant)
        self.menuAffichageRechercheET.setObjectName("menuAffichageRechercheET")
        self.menuMatiere = QtWidgets.QMenu(self.menubar)
        self.menuMatiere.setObjectName("menuMatiere")
        self.menuMiseaJourMat = QtWidgets.QMenu(self.menuMatiere)
        self.menuMiseaJourMat.setObjectName("menuMiseaJourMat")
        self.menuModifierMat = QtWidgets.QMenu(self.menuMiseaJourMat)
        self.menuModifierMat.setObjectName("menuModifierMat")
        self.menuAffichageRechercheMat = QtWidgets.QMenu(self.menuMatiere)
        self.menuAffichageRechercheMat.setObjectName("menuAffichageRechercheMat")
        self.menuNote = QtWidgets.QMenu(self.menubar)
        self.menuNote.setObjectName("menuNote")
        self.menuMiseaJourNT = QtWidgets.QMenu(self.menuNote)
        self.menuMiseaJourNT.setObjectName("menuMiseaJourNT")
        self.menuAffichageRechercheNT = QtWidgets.QMenu(self.menuNote)
        self.menuAffichageRechercheNT.setObjectName("menuAffichageRechercheNT")
        self.menuCalculEtAffichageNT = QtWidgets.QMenu(self.menubar)
        self.menuCalculEtAffichageNT.setObjectName("menuCalculEtAffichageNT")

        self.actionEnonce = QtWidgets.QAction(self.menufile)
        self.actionEnonce.setObjectName("actionEnonce")

        self.actionEnonce.triggered.connect(lambda: os.system("projet-2.pdf"))


        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAffichageEtudiant = QtWidgets.QAction(MainWindow)
        self.actionAffichageEtudiant.setObjectName("actionAffichageEtudiant")
        self.actionAffichageEtudiant = QtWidgets.QAction(MainWindow, triggered=lambda: self.openArg(ET.Etudiants,
                                                                                                    Ui_AffichageEtudiant))

        self.actionAjouterET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_AjoutEtudiant))
        self.actionAjouterET.setObjectName("actionAjouterET")

        self.actionAjouterET.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionAjouterET.setShortcutVisibleInContextMenu(False)

        self.actionSupprimerET = QtWidgets.QAction(MainWindow)
        self.actionSupprimerET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_SupEtudiantNumInscrit))
        self.actionSupprimerET.setObjectName("actionSupprimerET")
        self.actionSupprimerET.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSupprimerET.setShortcutVisibleInContextMenu(False)
        self.actionSupprimerParSectionET = QtWidgets.QAction(MainWindow)
        self.actionSupprimerParSectionET.setObjectName("actionSupprimerParSectionET")
        self.actionSupprimerParSectionET = QtWidgets.QAction(MainWindow,
                                                             triggered=lambda: self.open(Ui_SupEtudiantSection))

        self.actionEngALL = QtWidgets.QAction(MainWindow)
        self.actionEngALL.setObjectName("actionEngALL")

        self.actionEngALL.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionEngALL.setShortcutVisibleInContextMenu(False)

        self.actionEngALL.triggered.connect(lambda: EXET.EnregistrerTXT(ET.Etudiants, "Etudiant"))

        self.actionEngALL .triggered.connect(lambda: EXMat.EnregistrerTXT(Mat.Matieres,"Matiere") )
        self.actionEngALL .triggered.connect(lambda: EXNT.EnregistrerTXT(NT.Notes,"Note") )

        self.actionEngET = QtWidgets.QAction(MainWindow)
        self.actionEngET.setObjectName("actionEngET")
        self.actionEngET .triggered.connect(lambda: EXET.EnregistrerTXT(ET.Etudiants,"Etudiant"))

        self.actionEngMat = QtWidgets.QAction(MainWindow)
        self.actionEngMat.setObjectName("actionEngMat")
        self.actionEngMat .triggered.connect(lambda: EXMat.EnregistrerTXT(Mat.Matieres,"Matiere") )
        self.actionEngNT = QtWidgets.QAction(MainWindow)
        self.actionEngNT.setObjectName("actionEngNT")
        self.actionEngNT .triggered.connect(lambda: EXNT.EnregistrerTXT(NT.Notes,"Note") )

        self.actionEngSousET = QtWidgets.QAction(MainWindow)
        self.actionEngSousET.setObjectName("actionEngSousET")
       # self.actionEngSousET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_EnregistrementEtudiant))

        self.actionEngSousET.triggered.connect(lambda: EXET.Enregistrersous(ET.Etudiants))

        self.actionEngSousMat = QtWidgets.QAction(MainWindow)
        self.actionEngSousMat.setObjectName("actionEngSousMat")
        #self.actionEngSousMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_EnregistrementMatiere))
        self.actionEngSousMat.triggered.connect(lambda: EXMat.Enregistrersous(Mat.Matieres))
        self.actionEngSousNT = QtWidgets.QAction(MainWindow)
        self.actionEngSousNT.setObjectName("actionEngSousNT")
#        self.actionEngSousNT = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_EnregistrementNote))
        self.actionEngSousNT.triggered.connect(lambda: EXNT.Enregistrersous(NT.Notes))

        self.actionRecALL = QtWidgets.QAction(MainWindow)
        self.actionRecALL.setObjectName("actionRecALL")
        self.actionRecALL.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionRecALL.setShortcutVisibleInContextMenu(False)

        self.actionRecALL .triggered.connect(lambda: EXET.RecupererTXT("Etudiant"))
        self.actionRecALL.triggered.connect(lambda: EXMat.RecupererTXT("Matiere"))
        self.actionRecALL.triggered.connect(lambda: EXNT.RecupererTXT("Note"))


        self.actionRecET = QtWidgets.QAction(MainWindow)
        self.actionRecET.setObjectName("actionRecET")

        self.actionRecET .triggered.connect(lambda: EXET.RecupererTXT("Etudiant"))

        self.actionRecMat = QtWidgets.QAction(MainWindow)
        self.actionRecMat.setObjectName("actionRecMat")
        self.actionRecMat.triggered.connect(lambda: EXMat.RecupererTXT("Matiere"))
        self.actionRecNT = QtWidgets.QAction(MainWindow)
        self.actionRecNT.setObjectName("actionRecNT")
        self.actionRecNT.triggered.connect(lambda: EXNT.RecupererTXT("Note"))

        self.actionRecFichierET = QtWidgets.QAction(MainWindow)
        self.actionRecFichierET.setObjectName("actionRecFichierET")
        self.actionRecFichierET.triggered.connect(lambda: EXET.Importfrom())


        self.actionRecFichierMat = QtWidgets.QAction(MainWindow)
        self.actionRecFichierMat.setObjectName("actionRecFichierMat")
        self.actionRecFichierMat.triggered.connect(lambda: EXMat.Importfrom())

        self.actionRecFichierNT = QtWidgets.QAction(MainWindow)
        self.actionRecFichierNT.setObjectName("actionRecFichierNT")
        self.actionRecFichierNT.triggered.connect(lambda: EXNT.Importfrom())

        self.actionSuppressionParNiveauET = QtWidgets.QAction(MainWindow)
        self.actionSuppressionParNiveauET.setObjectName("actionSuppressionParNiveauET")
        self.actionSuppressionParNiveauET = QtWidgets.QAction(MainWindow,
                                                              triggered=lambda: self.open(Ui_SupEtudiantNiveau))
        self.actionSuppressionParNiveauEtSectionET = QtWidgets.QAction(MainWindow)
        self.actionSuppressionParNiveauEtSectionET.setObjectName("actionSuppressionParNiveauEtSectionET")
        self.actionSuppressionParNiveauEtSectionET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(
            Ui_SuppressionSection_Niveau))
        self.actionModTelephoneET = QtWidgets.QAction(MainWindow)
        self.actionModTelephoneET.setObjectName("actionModTelephoneET")
        self.actionModTelephoneET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_ModNumTelET))

        self.actionModMailET = QtWidgets.QAction(MainWindow)
        self.actionModMailET.setObjectName("actionModMailET")
        self.actionModMailET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_ModMailET))

        self.actionModAdresseET = QtWidgets.QAction(MainWindow)
        self.actionModAdresseET.setObjectName("actionModAdresseET")
        self.actionModAdresseET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_ModAdresseET))

        self.actionRechNumInscritET = QtWidgets.QAction(MainWindow)
        self.actionRechNumInscritET.setObjectName("actionRechNumInscritET")
        self.actionRechNumInscritET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_RechNumInscritET))
        self.actionAffichageSectionET = QtWidgets.QAction(MainWindow)
        self.actionAffichageSectionET.setObjectName("actionAffichageSectionET")
        self.actionAffichageSectionET = QtWidgets.QAction(MainWindow,
                                                          triggered=lambda: self.open(Ui_RechSectionET))

        self.actionAffichageSectionetNiveauET = QtWidgets.QAction(MainWindow)
        self.actionAffichageSectionetNiveauET.setObjectName("actionAffichageSectionetNiveauET")
        self.actionAffichageSectionetNiveauET = QtWidgets.QAction(MainWindow,
                                                                  triggered=lambda: self.open(Ui_RechSectionNiveauET))
        self.actionAffichageNiveauET = QtWidgets.QAction(MainWindow)
        self.actionAffichageNiveauET.setObjectName("actionAffichageNiveauET")

        self.actionAffichageNiveauET = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_RechNiveauET))
        self.actionAjouterMat = QtWidgets.QAction(MainWindow)
        self.actionAjouterMat.setObjectName("actionAjouterMat")
        self.actionAjouterMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_AjoutMatiere))
        self.actionAjouterMat.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionAjouterMat.setShortcutVisibleInContextMenu(False)

        self.actionSupprimerMat = QtWidgets.QAction(MainWindow)
        self.actionSupprimerMat.setObjectName("actionSupprimerMat")
        self.actionSupprimerMat.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSupprimerMat.setShortcutVisibleInContextMenu(False)
        self.actionSupprimerMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_SupMatiere))

        self.actionModDesigniationMat = QtWidgets.QAction(MainWindow)
        self.actionModDesigniationMat.setObjectName("actionModDesigniationMat")
        self.actionModDesigniationMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_ModDesignationMat))

        self.actionModCoefficient = QtWidgets.QAction(MainWindow)
        self.actionModCoefficient.setObjectName("actionModCoefficient")

        self.actionModCoefficient = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_ModCoefficientMat))
        self.actionAffichageMatiere = QtWidgets.QAction(MainWindow)
        self.actionAffichageMatiere.setObjectName("actionAffichageMatiere")

        self.actionAffichageMatiere = QtWidgets.QAction(MainWindow, triggered=lambda: self.openArg(Mat.Matieres,
                                                                                                   Ui_AffichageMatiere))

        self.actionRecFichierhCodeMat = QtWidgets.QAction(MainWindow)
        self.actionRecFichierhCodeMat.setObjectName("actionRecFichierhCodeMat")
        self.actionRecFichierhCodeMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_RechCodeMat))
        self.actionRecFichierhSectionMat = QtWidgets.QAction(MainWindow)
        self.actionRecFichierhSectionMat.setObjectName("actionRecFichierhSectionMat")
        self.actionRecFichierhSectionMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_RechSectionMat))

        self.actionAffichageSectionEtSemestreMat = QtWidgets.QAction(MainWindow)
        self.actionAffichageSectionEtSemestreMat.setObjectName("actionAffichageSectionEtSemestreMat")
        self.actionAffichageSectionEtSemestreMat = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(
            Ui_RechSectionSemestreMat))
        self.actionAjouterNT = QtWidgets.QAction(MainWindow)
        self.actionAjouterNT.setObjectName("actionAjouterNT")
        self.actionAjouterNT.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionAjouterNT.setShortcutVisibleInContextMenu(False)
        self.actionAjouterNT = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_AjoutNote))
        self.actionSupprimerNT = QtWidgets.QAction(MainWindow)
        self.actionSupprimerNT.setObjectName("actionSupprimerNT")
        self.actionSupprimerNT.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSupprimerNT.setShortcutVisibleInContextMenu(False)
        self.actionSupprimerNT = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_SupNote))

        self.actionModifierNT = QtWidgets.QAction(MainWindow)
        self.actionModifierNT.setObjectName("actionModifierNT")
        self.actionModifierNT = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_ModNote))
        self.actionAffichageNote = QtWidgets.QAction(MainWindow)
        self.actionAffichageNote.setObjectName("actionAffichageNote")
        self.actionAffichageNote = QtWidgets.QAction(MainWindow,
                                                     triggered=lambda: self.openArg(NT.Notes, Ui_AffichageNote))

        self.actionAffichageNumInscritNT = QtWidgets.QAction(MainWindow)
        self.actionAffichageNumInscritNT.setObjectName("actionAffichageNumInscritNT")
        self.actionAffichageNumInscritNT = QtWidgets.QAction(MainWindow,
                                                             triggered=lambda: self.open(Ui_RechNumInscritNT))

        self.actionAffichageSectionetNiveauNT = QtWidgets.QAction(MainWindow)
        self.actionAffichageSectionetNiveauNT.setObjectName("actionAffichageSectionetNiveauNT")
        self.actionAffichageSectionetNiveauNT = QtWidgets.QAction(MainWindow,
                                                                  triggered=lambda: self.open(Ui_RechSectionNiveauNT))

        self.actionAffichageNumInscritEtSemestreNT = QtWidgets.QAction(MainWindow)
        self.actionAffichageNumInscritEtSemestreNT.setObjectName("actionAffichageNumInscritEtSemestreNT")
        self.actionAffichageNumInscritEtSemestreNT = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(
            Ui_RechNumInscritSemestreNT))

        self.actionBulletinEtudiant = QtWidgets.QAction(MainWindow)
        self.actionBulletinEtudiant.setObjectName("actionBulletinEtudiant")
        self.actionBulletinEtudiant = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(Ui_SaisieNumInscritET))
        self.actionBulletinEtudiant.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionBulletinEtudiant.setShortcutVisibleInContextMenu(False)
        self.actionBulletinSemEtudiant = QtWidgets.QAction(MainWindow)
        self.actionBulletinSemEtudiant.setObjectName("actionBulletinSemEtudiant")
        self.actionBulletinSemEtudiant = QtWidgets.QAction(MainWindow,
                                                           triggered=lambda: self.open(Ui_RechNumInscritSemestre))

        self.actionEtudiantsAdmisSection = QtWidgets.QAction(MainWindow)

        self.actionEtudiantsAdmisSection.setObjectName("actionEtudiantsAdmisSection")
        self.actionEtudiantsAdmisSection = QtWidgets.QAction(MainWindow,
                                                             triggered=lambda: self.openArg(0, Ui_EtudiantAdmisSection))

        self.actionEtudiantsRedoublantsSection = QtWidgets.QAction(MainWindow)

        self.actionEtudiantsRedoublantsSection.setObjectName("actionEtudiantsRedoublantsSection")
        self.actionEtudiantsRedoublantsSection = QtWidgets.QAction(MainWindow, triggered=lambda: self.openArg(1,
                                                                                                              Ui_EtudiantAdmisSection))

        self.actionEtudiantsAdmisISIMM = QtWidgets.QAction(MainWindow)
        self.actionEtudiantsAdmisISIMM.setObjectName("actionEtudiantsAdmisISIMM")
        self.actionEtudiantsAdmisISIMM = QtWidgets.QAction(MainWindow,
                                                           triggered=lambda: self.open(Ui_AffichageResultat))
        self.actionEtudiantsRedoublantsISIMM = QtWidgets.QAction(MainWindow)
        self.actionEtudiantsRedoublantsISIMM.setObjectName("actionEtudiantsRedoublantsISIMM")

        self.actionEtudiantsRedoublantsISIMM = QtWidgets.QAction(MainWindow, triggered=lambda: self.openArg(0,
                                                                                                            Ui_AffichageResultat))
        self.actionMoyennesdSection = QtWidgets.QAction(MainWindow)
        self.actionMoyennesdSection.setObjectName("actionMoyennesdSection")
        self.actionMoyennesdSection = QtWidgets.QAction(MainWindow, triggered=lambda: self.open(
                                                                                                     Ui_MoyenneSection))
        self.menuEnregistrer.addAction(self.actionEngALL)

        self.menuEnregistrer.addAction(self.actionEngET)
        self.menuEnregistrer.addAction(self.actionEngMat)
        self.menuEnregistrer.addAction(self.actionEngNT)
        self.menuEnregistrerSous.addAction(self.actionEngSousET)
        self.menuEnregistrerSous.addAction(self.actionEngSousMat)
        self.menuEnregistrerSous.addAction(self.actionEngSousNT)

        self.menuRecuperer.addAction(self.actionRecALL)

        self.menuRecuperer.addAction(self.actionRecET)
        self.menuRecuperer.addAction(self.actionRecMat)
        self.menuRecuperer.addAction(self.actionRecNT)

        self.menuRecupererFichier.addAction(self.actionRecFichierET)
        self.menuRecupererFichier.addAction(self.actionRecFichierMat)
        self.menuRecupererFichier.addAction(self.actionRecFichierNT)
        self.menufile.addAction(self.menuEnregistrer.menuAction())
        self.menufile.addAction(self.menuRecuperer.menuAction())
        self.menufile.addAction(self.menuEnregistrerSous.menuAction())
        self.menufile.addAction(self.menuRecupererFichier.menuAction())
        self.menuSupprimerET.addAction(self.actionSupprimerET)
        self.menuSupprimerET.addAction(self.actionSupprimerParSectionET)
        self.menuSupprimerET.addAction(self.actionSuppressionParNiveauET)
        self.menuSupprimerET.addAction(self.actionSuppressionParNiveauEtSectionET)
        self.menuModifierET.addAction(self.actionModTelephoneET)
        self.menuModifierET.addAction(self.actionModMailET)
        self.menuModifierET.addAction(self.actionModAdresseET)
        self.menuMiseaJourET.addAction(self.actionAjouterET)
        self.menuMiseaJourET.addAction(self.menuSupprimerET.menuAction())
        self.menuMiseaJourET.addAction(self.menuModifierET.menuAction())
        self.menuAffichageRechercheET.addSeparator()
        self.menuAffichageRechercheET.addAction(self.actionAffichageEtudiant)
        self.menuAffichageRechercheET.addAction(self.actionRechNumInscritET)
        self.menuAffichageRechercheET.addAction(self.actionAffichageSectionET)
        self.menuAffichageRechercheET.addAction(self.actionAffichageNiveauET)
        self.menuAffichageRechercheET.addAction(self.actionAffichageSectionetNiveauET)
        self.menuEtudiant.addAction(self.menuMiseaJourET.menuAction())
        self.menuEtudiant.addAction(self.menuAffichageRechercheET.menuAction())
        self.menuModifierMat.addAction(self.actionModDesigniationMat)
        self.menuModifierMat.addAction(self.actionModCoefficient)
        self.menuMiseaJourMat.addAction(self.actionAjouterMat)
        self.menuMiseaJourMat.addAction(self.actionSupprimerMat)
        self.menuMiseaJourMat.addAction(self.menuModifierMat.menuAction())
        self.menuAffichageRechercheMat.addAction(self.actionAffichageMatiere)
        self.menuAffichageRechercheMat.addAction(self.actionRecFichierhCodeMat)
        self.menuAffichageRechercheMat.addAction(self.actionRecFichierhSectionMat)
        self.menuAffichageRechercheMat.addAction(self.actionAffichageSectionEtSemestreMat)
        self.menuMatiere.addAction(self.menuMiseaJourMat.menuAction())
        self.menuMatiere.addAction(self.menuAffichageRechercheMat.menuAction())
        self.menuMiseaJourNT.addAction(self.actionAjouterNT)
        self.menuMiseaJourNT.addAction(self.actionSupprimerNT)
        self.menuMiseaJourNT.addAction(self.actionModifierNT)
        self.menuAffichageRechercheNT.addAction(self.actionAffichageNote)
        self.menuAffichageRechercheNT.addAction(self.actionAffichageNumInscritNT)
        self.menuAffichageRechercheNT.addAction(self.actionAffichageSectionetNiveauNT)
        self.menuAffichageRechercheNT.addAction(self.actionAffichageNumInscritEtSemestreNT)
        self.menuNote.addAction(self.menuMiseaJourNT.menuAction())
        self.menuNote.addAction(self.menuAffichageRechercheNT.menuAction())
        self.menuCalculEtAffichageNT.addAction(self.actionBulletinEtudiant)
        self.menuCalculEtAffichageNT.addAction(self.actionBulletinSemEtudiant)
        self.menuCalculEtAffichageNT.addAction(self.actionEtudiantsAdmisSection)
        self.menuCalculEtAffichageNT.addAction(self.actionEtudiantsRedoublantsSection)
        self.menuCalculEtAffichageNT.addAction(self.actionEtudiantsAdmisISIMM)
        self.menuCalculEtAffichageNT.addAction(self.actionEtudiantsRedoublantsISIMM)
        self.menuCalculEtAffichageNT.addAction(self.actionMoyennesdSection)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEtudiant.menuAction())
        self.menubar.addAction(self.menuMatiere.menuAction())
        self.menubar.addAction(self.menuNote.menuAction())
        self.menubar.addAction(self.menuCalculEtAffichageNT.menuAction())
        self.menubar.addAction(self.actionEnonce)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projet Etudiant"))
        self.CreatedBy.setText(_translate("MainWindow", "© Created By EL Kamel Yassine"))
        self.IconEtudiant.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.IconNote.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        self.IconMatiere.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
        self.ButtonAffichageEtudiants.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ButtonAffichageEtudiants.setText(_translate("MainWindow", "Afficher tous les Etudiants"))
        self.AffichageMatiere.setText(_translate("MainWindow", "Afficher tous les Matieres"))
        self.AffichageNotes.setText(_translate("MainWindow", "Afficher tous les Notes"))

        self.menufile.setTitle(_translate("MainWindow", "File"))

        self.menuEnregistrer.setTitle(_translate("MainWindow", "Enregistrer"))
        self.menuRecuperer.setTitle(_translate("MainWindow", "Recuperer"))

        self.menuEnregistrerSous.setTitle(_translate("MainWindow", "Enregistrer sous"))
        self.menuRecupererFichier.setTitle(_translate("MainWindow", "Recuperer depuis un fichier"))
        self.menuEtudiant.setTitle(_translate("MainWindow", "Etudiant"))
        self.menuMiseaJourET.setTitle(_translate("MainWindow", "Mise à jour "))
        self.menuSupprimerET.setTitle(_translate("MainWindow", "Supprimer"))
        self.menuModifierET.setTitle(_translate("MainWindow", "Modifier"))
        self.menuAffichageRechercheET.setTitle(_translate("MainWindow", "Affichage/Recherche"))
        self.menuMatiere.setTitle(_translate("MainWindow", "Matière"))
        self.menuMiseaJourMat.setTitle(_translate("MainWindow", "Mise à jour"))
        self.menuModifierMat.setTitle(_translate("MainWindow", "Modifier"))
        self.menuAffichageRechercheMat.setTitle(_translate("MainWindow", "Affichage/Recherche"))
        self.menuNote.setTitle(_translate("MainWindow", "Note"))
        self.menuMiseaJourNT.setTitle(_translate("MainWindow", "Mise à jour"))
        self.menuAffichageRechercheNT.setTitle(_translate("MainWindow", "Affichage/Recherche"))
        self.menuCalculEtAffichageNT.setTitle(_translate("MainWindow", "Calcul et Affichage"))

        self.actionEnonce.setText(_translate("MainWindow", "Enonce de projet"))

        self.actionAffichageEtudiant.setText(_translate("MainWindow", "Afficher tous les étudiants"))
        self.actionAjouterET.setText(_translate("MainWindow", "Ajouter"))
        self.actionAjouterET.setShortcut(_translate("MainWindow", "Ctrl+E"))

        self.actionSupprimerET.setText(_translate("MainWindow", "Suppression d\'un étudiant"))
        self.actionSupprimerET.setShortcut(_translate("MainWindow", "Alt+E"))
        self.actionSupprimerParSectionET.setText(_translate("MainWindow", "Suppression des étudiants par section"))
        self.actionEngSousET.setText(_translate("MainWindow", "Etudiant"))
        self.actionEngSousMat.setText(_translate("MainWindow", "Matiere"))
        self.actionEngSousNT.setText(_translate("MainWindow", "Note"))
        self.actionEngALL.setText(_translate("MainWindow", "Enregistrer tous les fichers"))
        self.actionEngALL.setShortcut(_translate("MainWindow", "Ctrl+S"))

        self.actionEngET.setText(_translate("MainWindow", "Etudiant"))
        self.actionEngMat.setText(_translate("MainWindow", "Matiere"))
        self.actionEngNT.setText(_translate("MainWindow", "Note"))

        self.actionRecFichierET.setText(_translate("MainWindow", "Etudiant"))
        self.actionRecFichierMat.setText(_translate("MainWindow", "Matiere"))
        self.actionRecFichierNT.setText(_translate("MainWindow", "Note"))
        self.actionRecALL.setText(_translate("MainWindow", "Recuperer tous les fichers"))
        self.actionRecALL.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionRecET.setText(_translate("MainWindow", "Etudiant"))
        self.actionRecMat.setText(_translate("MainWindow", "Matiere"))
        self.actionRecNT.setText(_translate("MainWindow", "Note"))

        self.actionSuppressionParNiveauET.setText(_translate("MainWindow", "Suppression des étudiants par niveau"))
        self.actionSuppressionParNiveauEtSectionET.setText(
            _translate("MainWindow", "Suppression des étudiants par section et niveau"))
        self.actionModTelephoneET.setText(_translate("MainWindow", "Téléphone"))
        self.actionModMailET.setText(_translate("MainWindow", "Mail"))
        self.actionModAdresseET.setText(_translate("MainWindow", "Adresse"))
        self.actionRechNumInscritET.setText(_translate("MainWindow", "Recherche par numéro d\'inscription"))
        self.actionAffichageSectionET.setText(_translate("MainWindow", "Recherche par section"))
        self.actionAffichageNiveauET.setText(_translate("MainWindow", "Recherche par niveau"))
        self.actionAffichageSectionetNiveauET.setText(_translate("MainWindow", "Recherche par section et niveau"))
        self.actionAjouterMat.setText(_translate("MainWindow", "Ajouter"))
        self.actionAjouterMat.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionSupprimerMat.setText(_translate("MainWindow", "Supprimer une matiere"))
        self.actionSupprimerMat.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionModDesigniationMat.setText(_translate("MainWindow", "Nom"))
        self.actionModCoefficient.setText(_translate("MainWindow", "Coefficient"))
        self.actionAffichageMatiere.setText(_translate("MainWindow", "Afficher tous les matières"))
        self.actionRecFichierhCodeMat.setText(_translate("MainWindow", "Recherche par code"))
        self.actionRecFichierhSectionMat.setText(_translate("MainWindow", "Recherche par section"))
        self.actionAffichageSectionEtSemestreMat.setText(_translate("MainWindow", "Recherche par section et semestre"))
        self.actionAjouterNT.setText(_translate("MainWindow", "Ajouter"))
        self.actionAjouterNT.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSupprimerNT.setText(_translate("MainWindow", "Supprimer"))
        self.actionSupprimerNT.setShortcut(_translate("MainWindow", "Alt+N"))
        self.actionModifierNT.setText(_translate("MainWindow", "Modifier"))
        self.actionAffichageNote.setText(_translate("MainWindow", "Afficher tous les notes"))
        self.actionAffichageNumInscritNT.setText(_translate("MainWindow", "Recherche par numéro d\'inscription"))
        self.actionAffichageSectionetNiveauNT.setText(_translate("MainWindow", "Recherche par section et niveau"))
        self.actionAffichageNumInscritEtSemestreNT.setText(
            _translate("MainWindow", "Recherche par numéro inscription et semestre"))
        self.actionBulletinEtudiant.setText(_translate("MainWindow", "Bulletin de note d\'un étudiant"))
        self.actionBulletinEtudiant.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionBulletinSemEtudiant.setText(_translate("MainWindow", "Bulletin de note d\'un étudiant par semestre"))
        self.actionEtudiantsAdmisSection.setText(_translate("MainWindow", "Etudiants admis d\'une section donnée"))
        self.actionEtudiantsRedoublantsSection.setText(
            _translate("MainWindow", "Etudiants redoublants d\'une section donnée"))
        self.actionEtudiantsAdmisISIMM.setText(_translate("MainWindow", "Etudiants admis de L\'ISIMM"))
        self.actionEtudiantsRedoublantsISIMM.setText(_translate("MainWindow", "Etudiants redoublants de L\'ISIMM"))

        self.actionMoyennesdSection.setText(_translate("MainWindow", "Moyennes des étudiants d\'une section donnée"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

