# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModCoefficientMat.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Matiere as Mat

class Ui_ModCoefficientMat(object):
    
    def CoefficientObjects (self,A):
        self.Coefficient.setHidden(A)
        self.Coefficient_2.setHidden(A)
        self.pushButtonModifer.setHidden(A)
    
    def CodeObjects (self,A):
        self.Code.setHidden(A)
        self.Code_2.setHidden(A)
        self.pushButtonChercher.setHidden(A)
        self.label.setHidden(A)
    
    
    def setupUi(self, ModCoefficientMat):
        ModCoefficientMat.setObjectName("ModCoefficientMat")
        ModCoefficientMat.resize(585, 466)
        self.centralwidget = QtWidgets.QWidget(ModCoefficientMat)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Code = QtWidgets.QLineEdit(self.widget)
        self.Code.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.buttonChercher)
        self.Code_2 = QtWidgets.QLabel(self.widget)
        self.Code_2.setGeometry(QtCore.QRect(180, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code_2.setFont(font)
        self.Code_2.setObjectName("Code_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Matiereinexistante = QtWidgets.QLabel(self.widget)
        self.Matiereinexistante.setGeometry(QtCore.QRect(160, 70, 261, 31))
        self.Matiereinexistante.setObjectName("Matiereinexistante")
        self.Matiereinexistante.setHidden(True)
        
        self.infoinvalideCode = QtWidgets.QLabel(self.widget)
        self.infoinvalideCode.setGeometry(QtCore.QRect(170, 210, 241, 31))
        self.infoinvalideCode.setObjectName("infoinvalideCode")
        self.infoinvalideCode.setHidden(True)
        
        self.Coefficient = QtWidgets.QLineEdit(self.widget)
        self.Coefficient.setGeometry(QtCore.QRect(180, 180, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Coefficient.setFont(font)
        self.Coefficient.setObjectName("Coefficient")
        self.Coefficient_2 = QtWidgets.QLabel(self.widget)
        self.Coefficient_2.setGeometry(QtCore.QRect(180, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Coefficient_2.setFont(font)
        self.Coefficient_2.setObjectName("Coefficient_2")
        self.infoinvalideCoefficient = QtWidgets.QLabel(self.widget)
        self.infoinvalideCoefficient.setGeometry(QtCore.QRect(180, 210, 231, 31))
        self.infoinvalideCoefficient.setObjectName("infoinvalideCoefficient")
        self.infoinvalideCoefficient.setHidden(True)
        self.pushButtonModifer = QtWidgets.QPushButton(self.widget)
        self.pushButtonModifer.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonModifer.setObjectName("pushButtonModifer")
        self.pushButtonModifer.clicked.connect(self.buttonModifier)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 40, 461, 21))
        self.label.setObjectName("label")
        ModCoefficientMat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModCoefficientMat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        ModCoefficientMat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModCoefficientMat)
        self.statusbar.setObjectName("statusbar")
        ModCoefficientMat.setStatusBar(self.statusbar)
        self.CodeObjects (False)   
        self.CoefficientObjects (True)
        self.retranslateUi(ModCoefficientMat)
        QtCore.QMetaObject.connectSlotsByName(ModCoefficientMat)

    def retranslateUi(self, ModCoefficientMat):
        _translate = QtCore.QCoreApplication.translate
        ModCoefficientMat.setWindowTitle(_translate("ModCoefficientMat", "Modification de coefficient d'une matiere"))
        self.pushButtonChercher.setText(_translate("ModCoefficientMat", "Chercher"))
        self.Code_2.setText(_translate("ModCoefficientMat", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Code</span></p></body></html>"))
        self.Icon.setText(_translate("ModCoefficientMat", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
        self.Matiereinexistante.setText(_translate("ModCoefficientMat", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Matiere inexistante</span></p></body></html>"))
        self.infoinvalideCode.setText(_translate("ModCoefficientMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Code invalide</span></p></body></html>"))
        self.Coefficient_2.setText(_translate("ModCoefficientMat", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Nouvelle Coefficient</span></p></body></html>"))
        self.infoinvalideCoefficient.setText(_translate("ModCoefficientMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Coefficient invalide</span></p></body></html>"))
        self.pushButtonModifer.setText(_translate("ModCoefficientMat", "Modifier"))
        self.label.setText(_translate("ModCoefficientMat", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le code de la matiere à modifer</span></p></body></html>"))
    
    def buttonChercher(self):
        global Code
        Code=self.Code.text()
        if (Mat.SaisieCode(Code))and (Code in Mat.Matieres.keys()) :
            self.CodeObjects (True)   
            self.CoefficientObjects (False)
            self.Matiereinexistante.setHidden(True)  
            self.infoinvalideCode.setHidden(True)     
        elif not(Mat.SaisieCode(Code)):
            self.infoinvalideCode.setHidden(False)     
            self.Matiereinexistante.setHidden(True)
        elif not(Code  in Mat.Matieres.keys()):
            self.Matiereinexistante.setHidden(False) 
            self.infoinvalideCode.setHidden(True)
      

    
    def buttonModifier(self):
        Coefficient=self.Coefficient.text()
        if (Mat.SaisieCoefficient(Coefficient)) :
            Mat.Matieres[Code][0]=Coefficient  
            self.infoinvalideCoefficient.setHidden(True)     
        else:
            self.infoinvalideCoefficient.setHidden(False)
 

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModCoefficientMat = QtWidgets.QMainWindow()
    ui = Ui_ModCoefficientMat()
    ui.setupUi(ModCoefficientMat)
    ModCoefficientMat.show()
    sys.exit(app.exec_())

