# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModDesignationMat.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Matiere as Mat

class Ui_ModDesignationMat(object):
    
    def DesignationObjects (self,A):
        self.Designation.setHidden(A)
        self.Designation_2.setHidden(A)
        self.pushButtonModifer.setHidden(A)
    
    def CodeObjects (self,A):
        self.Code.setHidden(A)
        self.Code_2.setHidden(A)
        self.pushButtonChercher.setHidden(A)
        self.label.setHidden(A)
    
    
    def setupUi(self, ModDesignationMat):
        ModDesignationMat.setObjectName("ModDesignationMat")
        ModDesignationMat.resize(585, 466)
        self.centralwidget = QtWidgets.QWidget(ModDesignationMat)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Code = QtWidgets.QLineEdit(self.widget)
        self.Code.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.buttonChercher)
        self.Code_2 = QtWidgets.QLabel(self.widget)
        self.Code_2.setGeometry(QtCore.QRect(180, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code_2.setFont(font)
        self.Code_2.setObjectName("Code_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Matiereinexistante = QtWidgets.QLabel(self.widget)
        self.Matiereinexistante.setGeometry(QtCore.QRect(160, 70, 261, 31))
        self.Matiereinexistante.setObjectName("Matiereinexistante")
        self.Matiereinexistante.setHidden(True)
        
        self.infoinvalideCode = QtWidgets.QLabel(self.widget)
        self.infoinvalideCode.setGeometry(QtCore.QRect(170, 210, 241, 31))
        self.infoinvalideCode.setObjectName("infoinvalideCode")
        self.infoinvalideCode.setHidden(True)
        
        self.Designation = QtWidgets.QLineEdit(self.widget)
        self.Designation.setGeometry(QtCore.QRect(180, 180, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Designation.setFont(font)
        self.Designation.setObjectName("Designation")
        self.Designation_2 = QtWidgets.QLabel(self.widget)
        self.Designation_2.setGeometry(QtCore.QRect(180, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Designation_2.setFont(font)
        self.Designation_2.setObjectName("Designation_2")
        self.infoinvalideDesignation = QtWidgets.QLabel(self.widget)
        self.infoinvalideDesignation.setGeometry(QtCore.QRect(180, 210, 231, 31))
        self.infoinvalideDesignation.setObjectName("infoinvalideDesignation")
        self.infoinvalideDesignation.setHidden(True)
        self.pushButtonModifer = QtWidgets.QPushButton(self.widget)
        self.pushButtonModifer.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonModifer.setObjectName("pushButtonModifer")
        self.pushButtonModifer.clicked.connect(self.buttonModifier)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 40, 461, 21))
        self.label.setObjectName("label")
        ModDesignationMat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModDesignationMat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        ModDesignationMat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModDesignationMat)
        self.statusbar.setObjectName("statusbar")
        ModDesignationMat.setStatusBar(self.statusbar)
        self.CodeObjects (False)   
        self.DesignationObjects (True)
        self.retranslateUi(ModDesignationMat)
        QtCore.QMetaObject.connectSlotsByName(ModDesignationMat)

    def retranslateUi(self, ModDesignationMat):
        _translate = QtCore.QCoreApplication.translate
        ModDesignationMat.setWindowTitle(_translate("ModDesignationMat", "Modification de designation d'une matiere"))
        self.pushButtonChercher.setText(_translate("ModDesignationMat", "Chercher"))
        self.Code_2.setText(_translate("ModDesignationMat", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Code</span></p></body></html>"))
        self.Icon.setText(_translate("ModDesignationMat", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
        self.Matiereinexistante.setText(_translate("ModDesignationMat", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Matiere inexistante</span></p></body></html>"))
        self.infoinvalideCode.setText(_translate("ModDesignationMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Code invalide</span></p></body></html>"))
        self.Designation_2.setText(_translate("ModDesignationMat", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Nouvelle designation</span></p></body></html>"))
        self.infoinvalideDesignation.setText(_translate("ModDesignationMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Designation invalide</span></p></body></html>"))
        self.pushButtonModifer.setText(_translate("ModDesignationMat", "Modifier"))
        self.label.setText(_translate("ModDesignationMat", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le code de la matiere à modifer</span></p></body></html>"))
    
    def buttonChercher(self):
        global Code
        Code=self.Code.text()
        if (Mat.SaisieCode(Code))and (Code in Mat.Matieres.keys()) :
            self.CodeObjects (True)   
            self.DesignationObjects (False)
            self.Matiereinexistante.setHidden(True)  
            self.infoinvalideCode.setHidden(True)     
        elif not(Mat.SaisieCode(Code)):
            self.infoinvalideCode.setHidden(False)     
            self.Matiereinexistante.setHidden(True)
        elif not(Code  in Mat.Matieres.keys()):
            self.Matiereinexistante.setHidden(False) 
            self.infoinvalideCode.setHidden(True)
      

    
    def buttonModifier(self):
        Designation=self.Designation.text()
        if (Mat.SaisieDesignation(Designation)) :
            Mat.Matieres[Code][0]=Designation  
            self.infoinvalideDesignation.setHidden(True)     
        else:
            self.infoinvalideDesignation.setHidden(False)
    

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModDesignationMat = QtWidgets.QMainWindow()
    ui = Ui_ModDesignationMat()
    ui.setupUi(ModDesignationMat)
    ModDesignationMat.show()
    sys.exit(app.exec_())
