# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModNumTelET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator,QDoubleValidator,QFont
import Etudiant as ET

class Ui_ModNumTelET(object):
    
    def NumTelObjects (self,A):
        self.NumTel.setHidden(A)
        self.NumTel_2.setHidden(A)
        self.pushButtonModifer.setHidden(A)
    
    def NumInsritObjects (self,A):
        self.Numinscrit.setHidden(A)
        self.Numinscrit_2.setHidden(A)
        self.pushButtonChercher.setHidden(A)
        self.label.setHidden(A)
    
    def setupUi(self, ModNumTelET):
        ModNumTelET.setObjectName("ModNumTelET")
        ModNumTelET.resize(585, 466)
        self.centralwidget = QtWidgets.QWidget(ModNumTelET)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")


        self.widget.setObjectName("widget")
        self.Numinscrit = QtWidgets.QLineEdit(self.widget)
        self.Numinscrit.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Numinscrit.setFont(font)
        self.Numinscrit.setObjectName("Numinscrit")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.buttonChercher)
        
        
        self.Numinscrit_2 = QtWidgets.QLabel(self.widget)
        self.Numinscrit_2.setGeometry(QtCore.QRect(210, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Numinscrit_2.setFont(font)
        self.Numinscrit_2.setObjectName("Numinscrit_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(140, 75, 261, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        self.infoinvalideInscrit = QtWidgets.QLabel(self.widget)
        self.infoinvalideInscrit.setGeometry(QtCore.QRect(170, 210, 261, 31))
        self.infoinvalideInscrit.setObjectName("infoinvalideInscrit")
        self.infoinvalideInscrit.setHidden(True)
        self.NumTel = QtWidgets.QLineEdit(self.widget)
        self.NumTel.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumTel.setFont(font)
        self.NumTel.setObjectName("NumTel")
        self.NumTel_2 = QtWidgets.QLabel(self.widget)
        self.NumTel_2.setGeometry(QtCore.QRect(190, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumTel_2.setFont(font)
        self.NumTel_2.setObjectName("NumTel_2")
        self.infoinvalideTel = QtWidgets.QLabel(self.widget)
        self.infoinvalideTel.setGeometry(QtCore.QRect(170, 210, 261, 31))
        self.infoinvalideTel.setObjectName("infoinvalideTel")
        self.infoinvalideTel.setHidden(True)
        self.pushButtonModifer = QtWidgets.QPushButton(self.widget)
        self.pushButtonModifer.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonModifer.setObjectName("pushButtonModifer")
        #Numinscrit=self.Numinscrit.text()
        self.pushButtonModifer.clicked.connect(self.buttonModifier)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(110, 40, 461, 21))
        self.label.setObjectName("label")
        ModNumTelET.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModNumTelET)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        ModNumTelET.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModNumTelET)
        self.statusbar.setObjectName("statusbar")
        ModNumTelET.setStatusBar(self.statusbar)

        self.retranslateUi(ModNumTelET)
        QtCore.QMetaObject.connectSlotsByName(ModNumTelET)
        self.NumInsritObjects (False)   
        self.NumTelObjects (True)

       
    def retranslateUi(self, ModNumTelET):
        _translate = QtCore.QCoreApplication.translate
        ModNumTelET.setWindowTitle(_translate("ModNumTelET", "Modification du numero de telephone d'un étudiant"))
        self.pushButtonChercher.setText(_translate("ModNumTelET", "Chercher"))
        self.Numinscrit_2.setText(_translate("ModNumTelET", "<html><head/><body><p><span style=\" color:#ffffff;\">Numero d\'inscription</span></p></body></html>"))
        self.Icon.setText(_translate("ModNumTelET", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("ModNumTelET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">L\'étudiant n\'existe pas</span></p></body></html>"))
        self.infoinvalideInscrit.setText(_translate("ModNumTelET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Numero d\'inscription invalide</span></p></body></html>"))
        self.NumTel_2.setText(_translate("ModNumTelET", "<html><head/><body><p><span style=\" color:#ffffff;\">Nouveau numero de téléphone</span></p></body></html>"))
        self.infoinvalideTel.setText(_translate("ModNumTelET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Numero de téléphone invalide</span></p></body></html>"))
        self.pushButtonModifer.setText(_translate("ModNumTelET", "Modifier"))
        self.label.setText(_translate("ModNumTelET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le numero d\'inscription de l\'étudiant à modifer</span></p></body></html>"))


    
    def buttonChercher(self):
        global Numinscrit
        Numinscrit=self.Numinscrit.text()
        if (ET.SaisieNumInscrit(Numinscrit))and (Numinscrit in ET.Etudiants.keys()) :
            self.NumInsritObjects (True)   
            self.NumTelObjects (False)
            self.Letudiantnexistepas.setHidden(True)  
            self.infoinvalideInscrit.setHidden(True)     
        elif not(ET.SaisieNumInscrit(Numinscrit)):
            self.infoinvalideInscrit.setHidden(False)     
            self.Letudiantnexistepas.setHidden(True)
        elif not(Numinscrit  in ET.Etudiants.keys()):
            self.Letudiantnexistepas.setHidden(False) 
            self.infoinvalideInscrit.setHidden(True)
      

    
    def buttonModifier(self):
        NumTel=self.NumTel.text()
        if (ET.SaisieTelephone(NumTel)) :
            ET.Etudiants[Numinscrit][5]=NumTel  
            self.infoinvalideInscrit.setHidden(True)     
        else:
            self.infoinvalideTel.setHidden(False)
      


import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModNumTelET = QtWidgets.QMainWindow()
    ui = Ui_ModNumTelET()
    ui.setupUi(ModNumTelET)
    ModNumTelET.show()
    sys.exit(app.exec_())
