# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Note as NT
import Etudiant as ET
import Matiere as Mat

class Ui_ModNote(object):
    def ItemsObjects (self,A):
        self.NoteDS.setHidden(A)
        self.NoteDS_2.setHidden(A)
        self.NoteEX.setHidden(A)
        self.NoteEX_2.setHidden(A)
        
        self.pushButtonModifer.setHidden(A)
    
    def KeyObjects (self,A):
        self.Code.setHidden(A)
        self.Code_2.setHidden(A)
        self.pushButtonChercher.setHidden(A)
        self.label.setHidden(A)
    
    
    def setupUi(self, ModNote):
        ModNote.setObjectName("ModNote")
        ModNote.resize(585, 531)
        self.centralwidget = QtWidgets.QWidget(ModNote)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -4, 701, 821))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        font = QtGui.QFont()
        font.setPointSize(12) 
        self.NumInscrit = QtWidgets.QLabel(self.widget)
        self.NumInscrit.setFont(font)
        self.NumInscrit.setObjectName("NumInscrit")
        self.NumInscrit.setGeometry(QtCore.QRect(180, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit_2 = QtWidgets.QLineEdit(self.widget)
        self.NumInscrit_2.setFont(font)
        self.NumInscrit_2.setObjectName("NumInscrit_2")
        self.NumInscrit_2.setGeometry(QtCore.QRect(180, 200, 231, 31))  
        self.Code = QtWidgets.QLineEdit(self.widget)
        self.Code.setGeometry(QtCore.QRect(180, 300, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 400, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.buttonChercher)
        self.Code_2 = QtWidgets.QLabel(self.widget)
        self.Code_2.setGeometry(QtCore.QRect(180, 270, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code_2.setFont(font)
        self.Code_2.setObjectName("Code_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 60, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Noteinexistante = QtWidgets.QLabel(self.widget)
        self.Noteinexistante.setGeometry(QtCore.QRect(160, 120, 261, 31))
        self.Noteinexistante.setObjectName("Noteinexistante")
        self.Noteinexistante.setHidden (True)
        
        self.infoinvalideNumInscrit = QtWidgets.QLabel(self.widget)
        self.infoinvalideNumInscrit.setGeometry(QtCore.QRect(170, 230, 241, 31))
        self.infoinvalideNumInscrit.setObjectName("infoinvalideCode")
        self.infoinvalideNumInscrit.setHidden (True)
        
        self.infoinvalideCode = QtWidgets.QLabel(self.widget)
        self.infoinvalideCode.setGeometry(QtCore.QRect(170, 330, 241, 31))
        self.infoinvalideCode.setObjectName("infoinvalideCode")
        self.infoinvalideCode.setHidden (True)
        self.NoteDS = QtWidgets.QLineEdit(self.widget)
        self.NoteDS.setGeometry(QtCore.QRect(180, 300, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteDS.setFont(font)
        self.NoteDS.setObjectName("NoteDS")
        self.NoteDS_2 = QtWidgets.QLabel(self.widget)
        self.NoteDS_2.setGeometry(QtCore.QRect(180, 270, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteDS_2.setFont(font)
        self.NoteDS_2.setObjectName("NoteDS_2")
        self.infoinvalideNoteDS = QtWidgets.QLabel(self.widget)
        self.infoinvalideNoteDS.setGeometry(QtCore.QRect(180, 330, 231, 31))
        self.infoinvalideNoteDS.setObjectName("infoinvalideNoteDS")
        self.infoinvalideNoteDS.setHidden (True)
        self.infoinvalideNoteEX = QtWidgets.QLabel(self.widget)
        self.infoinvalideNoteEX.setGeometry(QtCore.QRect(180, 230, 231, 31))
        self.infoinvalideNoteEX.setObjectName("infoinvalideNoteEX")
       
        self.infoinvalideNoteEX.setHidden (True)
        self.pushButtonModifer = QtWidgets.QPushButton(self.widget)
        self.pushButtonModifer.setGeometry(QtCore.QRect(360, 400, 75, 23))
        self.pushButtonModifer.setObjectName("pushButtonModifer")
        
        self.pushButtonModifer.clicked.connect(self.buttonModifier)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(90, 30, 471, 61))
        self.label.setObjectName("label")
        self.NoteEX = QtWidgets.QLabel(self.widget)
        self.NoteEX.setGeometry(QtCore.QRect(180, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteEX.setFont(font)
        self.NoteEX.setObjectName("NoteEX")
        self.NoteEX_2 = QtWidgets.QLineEdit(self.widget)
        self.NoteEX_2.setGeometry(QtCore.QRect(180, 200, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoteEX_2.setFont(font)
        self.NoteEX_2.setObjectName("NoteEX_2")

        ModNote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModNote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        ModNote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModNote)
        self.statusbar.setObjectName("statusbar")
        ModNote.setStatusBar(self.statusbar)
        self.KeyObjects(False)
        self.ItemsObjects(True)
        self.retranslateUi(ModNote)
        QtCore.QMetaObject.connectSlotsByName(ModNote)

    def retranslateUi(self, ModNote):
        _translate = QtCore.QCoreApplication.translate
        ModNote.setWindowTitle(_translate("ModNote", "MainWindow"))
        elf.pushButtonChercher.setText(_translate("ModNote", "Chercher"))
        self.Code_2.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Code</span></p></body></html>"))
        self.Icon.setText(_translate("ModNote", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        self.Noteinexistante.setText(_translate("ModNote", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Note inexistante</span></p></body></html>"))
        self.infoinvalideCode.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Code invalide</span></p></body></html>"))
        
        self.infoinvalideNumInscrit.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Numero d'inscription invalide</span></p></body></html>"))
        
        self.NoteDS_2.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Nouvelle note DS</span></p></body></html>"))
        self.infoinvalideNoteDS.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Note DS invalide</span></p></body></html>"))
        self.infoinvalideNoteEX.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Note EX invalide</span></p></body></html>"))
        self.pushButtonModifer.setText(_translate("ModNote", "Modifier"))
        self.label.setText(_translate("ModNote", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le numero d\'inscription le code associeé a la note </span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">à modifer</span></p></body></html>"))
        self.NoteEX.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Nouvelle note EX</span></p></body></html>"))
        self.NumInscrit.setText(_translate("ModNote", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Numero d\'inscription</span></p></body></html>"))

    def buttonChercher(self):
        global NumInscrit
        global Code
        Code=self.Code.text()
        NumInscrit=self.NumInscrit_2.text()
        if (Mat.SaisieCode(Code))and (ET.SaisieNumInscrit(NumInscrit)) and((NumInscrit,Code) in NT.Notes.keys()) :
            self.KeyObjects (True)   
            self.ItemsObjects (False)
            self.Noteinexistante.setHidden(True)  
            self.infoinvalideCode.setHidden(True)
            self.infoinvalideNumInscrit.setHidden(True)
        if not(Mat.SaisieCode(Code)):
            self.infoinvalideCode.setHidden(False)     
            self.Noteinexistante.setHidden(True)
        else :
            self.infoinvalideCode.setHidden(True)
        if not(ET.SaisieNumInscrit(NumInscrit)):
            self.infoinvalideNumInscrit.setHidden(False)     
            self.Noteinexistante.setHidden(True)
        else :
            self.infoinvalideNumInscrit.setHidden(True)

        if not((NumInscrit,Code) in NT.Notes.keys()):
            self.Noteinexistante.setHidden(False) 
      

    
    def buttonModifier(self):
        NoteEX=self.NoteEX_2.text()
        NoteDS=self.NoteDS.text()

        if (NT.SaisieNote(NoteEX))and (NT.SaisieNote(NoteDS)) :
            NT.Notes[NumInscrit,Code][0]=NoteEX
            NT.Notes[NumInscrit,Code][1]=NoteDS  
            self.infoinvalideNoteDS.setHidden(True)
            self.infoinvalideNoteEX.setHidden(True)     
        if not (NT.SaisieNote(NoteEX)):
            self.infoinvalideNoteEX.setHidden(False)
        else:
            self.infoinvalideNoteEX.setHidden(True)
        if not (NT.SaisieNote(NoteDS)):
            self.infoinvalideNoteDS.setHidden(False)
        else:
            self.infoinvalideNoteDS.setHidden(True)    
    



import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModNote = QtWidgets.QMainWindow()
    ui = Ui_ModNote()
    ui.setupUi(ModNote)
    ModNote.show()
    sys.exit(app.exec_())
