# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MoyenneSection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Etudiant as ET
import Matiere as Mat
import Note as NT


def CalculMoyenneMat(keys):
    return ((float(NT.Notes[keys][0][::3])) * 0.25 + (float(NT.Notes[keys][1][::3])) * 0.75)


def CalculMoyenneGen(Numinscrits):
    Moy = 0
    Coefficinets = 0
    for keys in NT.Notes:
        if keys[0] == Numinscrits:
            Coefficinets += float(Mat.Matieres[keys[1]][2])
            Moy += CalculMoyenneMat(keys) * float(Mat.Matieres[keys[1]][2])
    Moy /= Coefficinets
    return (round(Moy, 3))


def CalculMoyenneSec(Section):
    T=[]
    Moy=0
    for key in NT.Notes:
        if ET.Etudiants[key[0]][6]==Section:
            T.append(CalculMoyenneGen(key[0]))
    for i in range (len (T)):
        Moy+=T[i]
    Moy/=len(T)
    return (round(Moy, 3))

class Ui_MoyenneSection(object):
    def setupUi(self, MoyenneSection):
        MoyenneSection.setObjectName("MoyenneSection")
        MoyenneSection.resize(590, 508)
        MoyenneSection.setStatusTip("")
        self.widget = QtWidgets.QWidget(MoyenneSection)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 951, 741))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.948, y2:0.936864, stop:0.522727 rgba(10, 204, 184, 250), stop:1 rgba(30, 169, 234)) \n"
"}")
        self.widget.setObjectName("widget")
        self.MoyenneSections = QtWidgets.QLabel(self.widget)
        self.MoyenneSections.setGeometry(QtCore.QRect(130, 40, 401, 51))
        self.MoyenneSections.setObjectName("MoyenneSections")
        self.ISIMMIcon = QtWidgets.QLabel(self.widget)
        self.ISIMMIcon.setGeometry(QtCore.QRect(280, 100, 101, 101))
        self.ISIMMIcon.setObjectName("ISIMMIcon")
        self.Section_2 = QtWidgets.QLabel(self.widget)
        self.Section_2.setGeometry(QtCore.QRect(60, 240, 171, 51))
        self.Section_2.setObjectName("Section_2")
        self.Moyenne = QtWidgets.QLabel(self.widget)
        self.Moyenne.setGeometry(QtCore.QRect(70, 340, 231, 31))
        self.Moyenne.setObjectName("Moyenne")
        self.Moyenne_2 = QtWidgets.QLabel(self.widget)
        self.Moyenne_2.setGeometry(QtCore.QRect(300, 340, 91, 31))
        self.Moyenne_2.setObjectName("Moyenne_2")
        self.Charger = QtWidgets.QPushButton(self.widget)
        self.Charger.setGeometry(QtCore.QRect(480, 390, 91, 31))
        self.Charger.setObjectName("Charger")
        self.Charger.clicked.connect(lambda:  self.getInfos())

        self.Section = QtWidgets.QLineEdit(self.widget)
        self.Section.setGeometry(QtCore.QRect(240, 250, 221, 31))
        self.Section.setObjectName("Section")

        self.retranslateUi(MoyenneSection)
        QtCore.QMetaObject.connectSlotsByName(MoyenneSection)




    def retranslateUi(self, MoyenneSection):
        _translate = QtCore.QCoreApplication.translate
        MoyenneSection.setWindowTitle(_translate("MoyenneSection", "Form"))
        self.MoyenneSections.setText(_translate("MoyenneSection", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">Moyenne d\'une Section</span></p></body></html>"))
        self.ISIMMIcon.setText(_translate("MoyenneSection", "<html><head/><body><p><img src=\":/newPrefix/ISIMM_LOGO.png\"/></p></body></html>"))
        self.Section_2.setText(_translate("MoyenneSection", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Secition :</span></p></body></html>"))
        self.Moyenne.setText(_translate("MoyenneSection", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Moyenne de la section:</span></p></body></html>"))
        self.Charger.setText(_translate("MoyenneSection", "Charger"))

    def getInfos(self):
        Section = self.Section.text()
        if (ET.SaisieSection(Section)):
            if (ET.RechercheParSection(ET.Etudiants, Section)):
                _translate = QtCore.QCoreApplication.translate
                self.Moyenne_2.setText(_translate("MoyenneSection","<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">" + str(CalculMoyenneSec(Section)) + "</span></p></body></html>"))
                #♣self.Letudiantnexistepas.setHidden(True)
                #self.infoinvalideSection.setHidden(True)
            #else:
                #self.Letudiantnexistepas.setHidden(False)
                #self.infoinvalideSection.setHidden(True)
        #else:
            #self.infoinvalideSection.setHidden(False)
            #self.Letudiantnexistepas.setHidden(True)


import icons_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MoyenneSection = QtWidgets.QWidget()
    ui = Ui_MoyenneSection()
    ui.setupUi(MoyenneSection)
    MoyenneSection.show()
    sys.exit(app.exec_())
