# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaperLeNiveauET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AffichageEtudiant import Ui_AffichageEtudiant
import Etudiant as ET


def Keys (Niveau):
    Tab=[]
    for key in ET.Etudiants:
        if (ET.Etudiants[key][7]==Niveau) :
            Tab.append(key)
    return Tab
    

class Ui_RechNiveauET(object):
    def openAffichageEtudiant(self,dict):
        self.window=QtWidgets.QMainWindow()
        self.ui= Ui_AffichageEtudiant()
        self.ui.setupUi(self.window,dict)
        self.window.show()

    def setupUi(self, RechNiveauET):  
        RechNiveauET.setObjectName("RechNiveauET")
        RechNiveauET.resize(556, 444)
        self.centralwidget = QtWidgets.QWidget(RechNiveauET)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Niveau = QtWidgets.QLineEdit(self.widget)
        self.Niveau.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau.setFont(font)
        self.Niveau.setObjectName("Niveau")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.getInfos)
        
        self.Niveau_2 = QtWidgets.QLabel(self.widget)
        self.Niveau_2.setGeometry(QtCore.QRect(180, 140, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau_2.setFont(font)
        self.Niveau_2.setObjectName("Niveau_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(130, 70, 261, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        self.infoinvalideNiveau = QtWidgets.QLabel(self.widget)
        self.infoinvalideNiveau.setGeometry(QtCore.QRect(170, 210, 251, 31))
        self.infoinvalideNiveau.setObjectName("infoinvalideNiveau")
        self.infoinvalideNiveau.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 40, 361, 21))
        self.label.setObjectName("label")
        RechNiveauET.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RechNiveauET)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        RechNiveauET.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RechNiveauET)
        self.statusbar.setObjectName("statusbar")
        RechNiveauET.setStatusBar(self.statusbar)

        self.retranslateUi(RechNiveauET)
        QtCore.QMetaObject.connectSlotsByName(RechNiveauET)

    def retranslateUi(self, RechNiveauET):
        _translate = QtCore.QCoreApplication.translate
        RechNiveauET.setWindowTitle(_translate("RechNiveauET", "Recherche par niveau"))
        self.pushButtonChercher.setText(_translate("RechNiveauET", "Chercher"))
        self.Niveau_2.setText(_translate("RechNiveauET", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Niveau</span></p></body></html>"))
        self.Icon.setText(_translate("RechNiveauET", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("RechNiveauET", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Niveau inexistant</span></p></body></html>"))
        self.infoinvalideNiveau.setText(_translate("RechNiveauET", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Niveau invalide</span></p></body></html>"))
        self.label.setText(_translate("RechNiveauET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le Niveau de l\'étudiant</span></p></body></html>"))
    def getInfos(self):
        Niveau=self.Niveau.text()
        dict={}
        if (ET.SaisieNiveauEtude(Niveau)) :
            if (ET.RechercheParNiveau(ET.Etudiants,Niveau)): 
                Tab=Keys(Niveau)
                for i in Tab:
                    dict.update ({i:ET.Etudiants[i]})
                self.openAffichageEtudiant(dict)
                self.Letudiantnexistepas.setHidden(True)
                self.infoinvalideNiveau.setHidden(True)
            else :
                self.Letudiantnexistepas.setHidden(False)
                self.infoinvalideNiveau.setHidden(True)
        else:
            self.infoinvalideNiveau.setHidden(False)
            self.Letudiantnexistepas.setHidden(True)
        print (ET.Etudiants)

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    RechNiveauET = QtWidgets.QMainWindow()
    ui = Ui_RechNiveauET()
    ui.setupUi(RechNiveauET)
    RechNiveauET.show()
    sys.exit(app.exec_())