# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaperLeSemestreET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Dict
from PyQt5 import QtCore, QtGui, QtWidgets
from AffichageMatiere import Ui_AffichageMatiere
import Matiere as Mat


def KeysSem (Semestre):
    Tab=[]
    for key in Mat.Matieres:
        if (Mat.Matieres[key][3]==Semestre) :
            Tab.append(key)
    return Tab

def KeysSec (Section):
    Tab=[]
    for key in Mat.Matieres:
        if (Mat.Matieres[key][1]==Section) :
            Tab.append(key)
    return Tab


class Ui_RechSectionSemestreMat(object):
    def openAffichageMatiere(self,dict):
        self.window=QtWidgets.QMainWindow()
        self.ui= Ui_AffichageMatiere()
        self.ui.setupUi(self.window,dict)
        self.window.show()

    def setupUi(self, RechSectionSemestreMat):  
        RechSectionSemestreMat.setObjectName("RechSectionSemestreMat")
        RechSectionSemestreMat.resize(556, 444)
        self.centralwidget = QtWidgets.QWidget(RechSectionSemestreMat)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 710, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        
        self.Section = QtWidgets.QLineEdit(self.widget)
        self.Section.setGeometry(QtCore.QRect(180, 150, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section.setFont(font)
        self.Section.setObjectName("Section")
        
        self.Semestre = QtWidgets.QLineEdit(self.widget)
        self.Semestre.setGeometry(QtCore.QRect(180, 250, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Semestre.setFont(font)
        self.Semestre.setObjectName("Semestre")
        
        
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.getInfos)
        
        
        self.Section_2 = QtWidgets.QLabel(self.widget)
        self.Section_2.setGeometry(QtCore.QRect(180, 120, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section_2.setFont(font)
        self.Section_2.setObjectName("Section_2")
        

        self.Semestre_2 = QtWidgets.QLabel(self.widget)
        self.Semestre_2.setGeometry(QtCore.QRect(180, 220, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Semestre_2.setFont(font)
        self.Semestre_2.setObjectName("Semestre_2")
        
        
        
        
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Matiereinexistante = QtWidgets.QLabel(self.widget)
        self.Matiereinexistante.setGeometry(QtCore.QRect(110, 70, 450, 31))
        self.Matiereinexistante.setObjectName("Matiereinexistante")
        self.Matiereinexistante.setHidden(True)
        
        self.infoinvalideSection = QtWidgets.QLabel(self.widget)
        self.infoinvalideSection.setGeometry(QtCore.QRect(170, 180, 251, 31))
        self.infoinvalideSection.setObjectName("infoinvalideSection")
        self.infoinvalideSection.setHidden(True)
        
        self.infoinvalideSemestre = QtWidgets.QLabel(self.widget)
        self.infoinvalideSemestre.setGeometry(QtCore.QRect(170, 280, 251, 31))
        self.infoinvalideSemestre.setObjectName("infoinvalideSemestre")
        self.infoinvalideSemestre.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 40, 390, 21))
        self.label.setObjectName("label")
        RechSectionSemestreMat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RechSectionSemestreMat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        RechSectionSemestreMat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RechSectionSemestreMat)
        self.statusbar.setObjectName("statusbar")
        RechSectionSemestreMat.setStatusBar(self.statusbar)

        self.retranslateUi(RechSectionSemestreMat)
        QtCore.QMetaObject.connectSlotsByName(RechSectionSemestreMat)

    def retranslateUi(self, RechSectionSemestreMat):
        _translate = QtCore.QCoreApplication.translate
        RechSectionSemestreMat.setWindowTitle(_translate("RechSectionSemestreMat", "Recherche par section et Semestre"))
        
        self.pushButtonChercher.setText(_translate("RechSectionSemestreMat", "Chercher"))
        
        self.Section_2.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Section</span></p></body></html>"))
        
        self.Semestre_2.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Semestre</span></p></body></html>"))
        
        
        self.Icon.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
        self.Matiereinexistante.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Aucune matiere ne fait partie de cette catégorie.</span></p></body></html>"))
        self.infoinvalideSection.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Section invalide</span></p></body></html>"))
        
        self.infoinvalideSemestre.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Semestre invalide</span></p></body></html>"))
        self.label.setText(_translate("RechSectionSemestreMat", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez la section et la Semestre de la matiere</span></p></body></html>"))
    def getInfos(self):
        Semestre=(self.Semestre.text()).upper()
        Section=self.Section.text()
        dictSec={}
        dictSem={}
        print (Section)
        if (Mat.SaisieSemestre(Semestre)and Mat.SaisieSection(Section)) :
            if (Mat.RechercheParSemestre(Mat.Matieres,Semestre) and Mat.RechercheParSection(Mat.Matieres,Section) ): 
                TabSec=KeysSec(Section)
                TabSem=KeysSem(Semestre)
                dictSec.update ({i:Mat.Matieres[i] for i in TabSec})
                dictSem.update ({i:Mat.Matieres[i] for i in TabSem})
                print (dictSem)
                print (dictSec)
                Dict = {x:dictSec[x] for x in dictSec 
                              if x in dictSem}
                
                self.openAffichageMatiere(Dict)
                self.Matiereinexistante.setHidden(True)
                self.infoinvalideSemestre.setHidden(True)
                self.infoinvalideSection.setHidden(True)
                
            else :
                self.Matiereinexistante.setHidden(False)
                self.infoinvalideSemestre.setHidden(True)
                self.infoinvalideSection.setHidden(True)
        if not (Mat.SaisieSemestre(Semestre)):
            self.infoinvalideSemestre.setHidden(False)
            
        else:
            self.infoinvalideSemestre.setHidden(True)
        
        
        if not (Mat.SaisieSection(Section)):
            self.infoinvalideSection.setHidden(False)
            
        else:
            self.infoinvalideSection.setHidden(True)
        
                
        #print (Mat.Matieres)

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    RechSectionSemestreMat = QtWidgets.QMainWindow()
    ui = Ui_RechSectionSemestreMat()
    ui.setupUi(RechSectionSemestreMat)
    RechSectionSemestreMat.show()
    sys.exit(app.exec_())