# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaperLeSemestreET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Dict
from PyQt5 import QtCore, QtGui, QtWidgets
from AffichageNote import Ui_AffichageNote
import Etudiant as ET
import Note as NT
import Matiere as Mat


class Ui_RechNumInscritSemestreNT(object):
    def openAffichageNote(self,dict):
        self.window=QtWidgets.QMainWindow()
        self.ui= Ui_AffichageNote()
        self.ui.setupUi(self.window,dict)
        self.window.show()

    def setupUi(self, RechNumInscritSemestreNT):  
        RechNumInscritSemestreNT.setObjectName("RechNumInscritSemestreNT")
        RechNumInscritSemestreNT.resize(556, 500)
        self.centralwidget = QtWidgets.QWidget(RechNumInscritSemestreNT)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 710, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        
        self.NumInscrit = QtWidgets.QLineEdit(self.widget)
        self.NumInscrit.setGeometry(QtCore.QRect(180, 180, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit.setFont(font)
        self.NumInscrit.setObjectName("NumInscrit")
        
        self.Semestre = QtWidgets.QLineEdit(self.widget)
        self.Semestre.setGeometry(QtCore.QRect(180, 280, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Semestre.setFont(font)
        self.Semestre.setObjectName("Semestre")
        
        
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 360, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.getInfos)
        
        
        self.NumInscrit_2 = QtWidgets.QLabel(self.widget)
        self.NumInscrit_2.setGeometry(QtCore.QRect(180, 150, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit_2.setFont(font)
        self.NumInscrit_2.setObjectName("NumInscrit_2")
        

        self.Semestre_2 = QtWidgets.QLabel(self.widget)
        self.Semestre_2.setGeometry(QtCore.QRect(180, 250, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Semestre_2.setFont(font)
        self.Semestre_2.setObjectName("Semestre_2")
        
        
        
        
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(20, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(110, 100, 450, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        
        self.infoinvalideNumInscrit = QtWidgets.QLabel(self.widget)
        self.infoinvalideNumInscrit.setGeometry(QtCore.QRect(170, 210, 251, 31))
        self.infoinvalideNumInscrit.setObjectName("infoinvalideNumInscrit")
        self.infoinvalideNumInscrit.setHidden(True)
        
        self.infoinvalideSemestre = QtWidgets.QLabel(self.widget)
        self.infoinvalideSemestre.setGeometry(QtCore.QRect(170, 310, 251, 31))
        self.infoinvalideSemestre.setObjectName("infoinvalideSemestre")
        self.infoinvalideSemestre.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 15, 380, 100))
        self.label.setObjectName("label")
        RechNumInscritSemestreNT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RechNumInscritSemestreNT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        RechNumInscritSemestreNT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RechNumInscritSemestreNT)
        self.statusbar.setObjectName("statusbar")
        RechNumInscritSemestreNT.setStatusBar(self.statusbar)

        self.retranslateUi(RechNumInscritSemestreNT)
        QtCore.QMetaObject.connectSlotsByName(RechNumInscritSemestreNT)

    def retranslateUi(self, RechNumInscritSemestreNT):
        _translate = QtCore.QCoreApplication.translate
        RechNumInscritSemestreNT.setWindowTitle(_translate("RechNumInscritSemestreNT", "Recherche par NumInscrit et Semestre"))
        
        self.pushButtonChercher.setText(_translate("RechNumInscritSemestreNT", "Chercher"))
        
        self.NumInscrit_2.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Numero d'inscription</span></p></body></html>"))
        
        self.Semestre_2.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Semestre</span></p></body></html>"))
        
        
        self.Icon.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Aucun étudiant ne fait partie de cette catégorie.</span></p></body></html>"))
        self.infoinvalideNumInscrit.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">NumInscrit invalide</span></p></body></html>"))
        
        self.infoinvalideSemestre.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Semestre invalide</span></p></body></html>"))
        #self.label.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le numero d'inscription et la Semestre \n\t de l\'étudiant</span></p></body></html>"))
    
        self.label.setText(_translate("RechNumInscritSemestreNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Tapez le numero d\'inscription et la Semestre</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\"> de l\'étudiant</span></p></body></html>"))
    
    def getInfos(self):
        NumInscrit=self.NumInscrit.text()
        Semestre=(self.Semestre.text()).upper()
        if (Mat.SaisieSemestre(Semestre)and ET.SaisieNumInscrit(NumInscrit)) : 
            Dict = {x:NT.Notes[x] for x in NT.Notes 
                            if x[0]==NumInscrit and Mat.Matieres[x[1]][3]==Semestre }
            if Dict : 
                self.openAffichageNote(Dict)
                self.Letudiantnexistepas.setHidden(True)
                self.infoinvalideSemestre.setHidden(True)
                self.infoinvalideNumInscrit.setHidden(True)
            else :
                self.Letudiantnexistepas.setHidden(False)
        if not (Mat.SaisieSemestre(Semestre)):
            self.infoinvalideSemestre.setHidden(False)
            
        else:
            self.infoinvalideSemestre.setHidden(True)
        
        if not (ET.SaisieNumInscrit(NumInscrit)):
            self.infoinvalideNumInscrit.setHidden(False)
            
        else:
            self.infoinvalideNumInscrit.setHidden(True)
        

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    RechNumInscritSemestreNT = QtWidgets.QMainWindow()
    ui = Ui_RechNumInscritSemestreNT()
    ui.setupUi(RechNumInscritSemestreNT)
    RechNumInscritSemestreNT.show()
    sys.exit(app.exec_())
