# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaperLeNiveauET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Dict
from PyQt5 import QtCore, QtGui, QtWidgets
from AffichageNote import Ui_AffichageNote
import Etudiant as ET
import Note as NT


def KeysNiv (Niveau):
    Tab=[]
    for key in ET.Etudiants:
        if (ET.Etudiants[key][7]==Niveau) :
            Tab.append(key)
    return Tab

def KeysSec (Section):
    Tab=[]
    for key in ET.Etudiants:
        if (ET.Etudiants[key][6]==Section) :
            Tab.append(key)
    return Tab


class Ui_RechSectionNiveauNT(object):
    def openAffichageNote(self,dict):
        self.window=QtWidgets.QMainWindow()
        self.ui= Ui_AffichageNote()
        self.ui.setupUi(self.window,dict)
        self.window.show()

    def setupUi(self, RechSectionNiveauNT):  
        RechSectionNiveauNT.setObjectName("RechSectionNiveauNT")
        RechSectionNiveauNT.resize(556, 444)
        self.centralwidget = QtWidgets.QWidget(RechSectionNiveauNT)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 710, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        
        self.Section = QtWidgets.QLineEdit(self.widget)
        self.Section.setGeometry(QtCore.QRect(180, 150, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section.setFont(font)
        self.Section.setObjectName("Section")
        
        self.Niveau = QtWidgets.QLineEdit(self.widget)
        self.Niveau.setGeometry(QtCore.QRect(180, 250, 231, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau.setFont(font)
        self.Niveau.setObjectName("Niveau")
        
        
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.getInfos)
        
        
        self.Section_2 = QtWidgets.QLabel(self.widget)
        self.Section_2.setGeometry(QtCore.QRect(180, 120, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section_2.setFont(font)
        self.Section_2.setObjectName("Section_2")
        

        self.Niveau_2 = QtWidgets.QLabel(self.widget)
        self.Niveau_2.setGeometry(QtCore.QRect(180, 220, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau_2.setFont(font)
        self.Niveau_2.setObjectName("Niveau_2")
        
        
        
        
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(110, 70, 450, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        
        self.infoinvalideSection = QtWidgets.QLabel(self.widget)
        self.infoinvalideSection.setGeometry(QtCore.QRect(170, 180, 251, 31))
        self.infoinvalideSection.setObjectName("infoinvalideSection")
        self.infoinvalideSection.setHidden(True)
        
        self.infoinvalideNiveau = QtWidgets.QLabel(self.widget)
        self.infoinvalideNiveau.setGeometry(QtCore.QRect(170, 280, 251, 31))
        self.infoinvalideNiveau.setObjectName("infoinvalideNiveau")
        self.infoinvalideNiveau.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 40, 361, 21))
        self.label.setObjectName("label")
        RechSectionNiveauNT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RechSectionNiveauNT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        RechSectionNiveauNT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RechSectionNiveauNT)
        self.statusbar.setObjectName("statusbar")
        RechSectionNiveauNT.setStatusBar(self.statusbar)

        self.retranslateUi(RechSectionNiveauNT)
        QtCore.QMetaObject.connectSlotsByName(RechSectionNiveauNT)

    def retranslateUi(self, RechSectionNiveauNT):
        _translate = QtCore.QCoreApplication.translate
        RechSectionNiveauNT.setWindowTitle(_translate("RechSectionNiveauNT", "Recherche par section et niveau"))
        
        self.pushButtonChercher.setText(_translate("RechSectionNiveauNT", "Chercher"))
        
        self.Section_2.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Section</span></p></body></html>"))
        
        self.Niveau_2.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Niveau</span></p></body></html>"))
        
        
        self.Icon.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Aucun étudiant ne fait partie de cette catégorie.</span></p></body></html>"))
        self.infoinvalideSection.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Section invalide</span></p></body></html>"))
        
        self.infoinvalideNiveau.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Niveau invalide</span></p></body></html>"))
        self.label.setText(_translate("RechSectionNiveauNT", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez la section et le niveau de l\'étudiant</span></p></body></html>"))
    def getInfos(self):
        Niveau=self.Niveau.text()
        Section=self.Section.text()
        dictSec={}
        dictNiv={}
        print (Section)
        if (ET.SaisieNiveauEtude(Niveau)and ET.SaisieSection(Section)) :
            if (ET.RechercheParNiveau(ET.Etudiants,Niveau) and ET.RechercheParSection(ET.Etudiants,Section) ): 
                TabSec=KeysSec(Section)
                TabNiv=KeysNiv(Niveau)
                dictSec.update ({i:ET.Etudiants[i] for i in TabSec})
                dictNiv.update ({i:ET.Etudiants[i] for i in TabNiv})
                DictET = {x:dictSec[x] for x in dictSec 
                              if x in dictNiv}
                
                Dict ={x:NT.Notes[x] for x in NT.Notes 
                              if x[0] in DictET }
                self.openAffichageNote(Dict)
                self.Letudiantnexistepas.setHidden(True)
                self.infoinvalideNiveau.setHidden(True)
                self.infoinvalideSection.setHidden(True)
                
            else :
                self.Letudiantnexistepas.setHidden(False)
                self.infoinvalideNiveau.setHidden(True)
                self.infoinvalideSection.setHidden(True)
        if not (ET.SaisieNiveauEtude(Niveau)):
            self.infoinvalideNiveau.setHidden(False)
            
        else:
            self.infoinvalideNiveau.setHidden(True)
        
        
        if not (ET.SaisieSection(Section)):
            self.infoinvalideSection.setHidden(False)
            
        else:
            self.infoinvalideSection.setHidden(True)
        

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    RechSectionNiveauNT = QtWidgets.QMainWindow()
    ui = Ui_RechSectionNiveauNT()
    ui.setupUi(RechSectionNiveauNT)
    RechSectionNiveauNT.show()
    sys.exit(app.exec_())
