# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaperLeSectionET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from AffichageEtudiant import Ui_AffichageEtudiant
import Etudiant as ET


def Keys (Section):
    Tab=[]
    for key in ET.Etudiants:
        if (ET.Etudiants[key][6]==Section) :
            Tab.append(key)
    return Tab
    

class Ui_RechSectionET(object):
    def openAffichageEtudiant(self,dict):
        self.window=QtWidgets.QMainWindow()
        self.ui= Ui_AffichageEtudiant()
        self.ui.setupUi(self.window,dict)
        self.window.show()

    def setupUi(self, RechSectionET):  
        RechSectionET.setObjectName("RechSectionET")
        RechSectionET.resize(556, 444)
        self.centralwidget = QtWidgets.QWidget(RechSectionET)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.Section = QtWidgets.QLineEdit(self.widget)
        self.Section.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section.setFont(font)
        self.Section.setObjectName("Section")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.getInfos)
        
        self.Section_2 = QtWidgets.QLabel(self.widget)
        self.Section_2.setGeometry(QtCore.QRect(180, 140, 225, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section_2.setFont(font)
        self.Section_2.setObjectName("Section_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(130, 70, 261, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        self.infoinvalideSection = QtWidgets.QLabel(self.widget)
        self.infoinvalideSection.setGeometry(QtCore.QRect(170, 210, 251, 31))
        self.infoinvalideSection.setObjectName("infoinvalideSection")
        self.infoinvalideSection.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 40, 361, 21))
        self.label.setObjectName("label")
        RechSectionET.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RechSectionET)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        RechSectionET.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RechSectionET)
        self.statusbar.setObjectName("statusbar")
        RechSectionET.setStatusBar(self.statusbar)

        self.retranslateUi(RechSectionET)
        QtCore.QMetaObject.connectSlotsByName(RechSectionET)

    def retranslateUi(self, RechSectionET):
        _translate = QtCore.QCoreApplication.translate
        RechSectionET.setWindowTitle(_translate("RechSectionET", "Recherche par section"))
        self.pushButtonChercher.setText(_translate("RechSectionET", "Chercher"))
        self.Section_2.setText(_translate("RechSectionET", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Section</span></p></body></html>"))
        self.Icon.setText(_translate("RechSectionET", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("RechSectionET", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Section inexistante</span></p></body></html>"))
        self.infoinvalideSection.setText(_translate("RechSectionET", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Section invalide</span></p></body></html>"))
        self.label.setText(_translate("RechSectionET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez la section de l\'étudiant</span></p></body></html>"))
    def getInfos(self):
        Section=self.Section.text()
        dict={}
        if (ET.SaisieSection(Section)) :
            if (ET.RechercheParSection(ET.Etudiants,Section)): 
                Tab=Keys(Section)
                for i in Tab:
                    dict.update ({i:ET.Etudiants[i]})
                self.openAffichageEtudiant(dict)
                self.Letudiantnexistepas.setHidden(True)
                self.infoinvalideSection.setHidden(True)
            else :
                self.Letudiantnexistepas.setHidden(False)
                self.infoinvalideSection.setHidden(True)
        else:
            self.infoinvalideSection.setHidden(False)
            self.Letudiantnexistepas.setHidden(True)
   

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    RechSectionET = QtWidgets.QMainWindow()
    ui = Ui_RechSectionET()
    ui.setupUi(RechSectionET)
    RechSectionET.show()
    sys.exit(app.exec_())