# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecupererationET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import Matiere as Mat
from Exporting_Matiere import RecupererTXT, RecupererCSV


class Ui_RecupererationMatiere(object):
    def setupUi(self, RecupererationMatiere):
        RecupererationMatiere.setObjectName("RecupererationMatiere")
        RecupererationMatiere.resize(585, 466)
        self.centralwidget = QtWidgets.QWidget(RecupererationMatiere)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
                                  "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
                                  " }")
        self.widget.setObjectName("widget")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 40, 101, 101))
        self.Icon.setObjectName("Icon")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 50, 461, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(390, 200, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.NomFichier = QtWidgets.QLineEdit(self.widget)
        self.NomFichier.setGeometry(QtCore.QRect(150, 199, 221, 21))
        self.NomFichier.setObjectName("NomFichie")
        self.ButtonRecuperer = QtWidgets.QPushButton(self.widget)
        self.ButtonRecuperer.setGeometry(QtCore.QRect(404, 300, 101, 31))
        self.ButtonRecuperer.setStyleSheet("")
        self.ButtonRecuperer.setObjectName("ButtonRecuperer")
        self.ButtonRecuperer.clicked.connect(lambda: self.Recuperer())
        self.TaperLeNom = QtWidgets.QLabel(self.widget)
        self.TaperLeNom.setGeometry(QtCore.QRect(150, 160, 221, 31))
        self.TaperLeNom.setObjectName("TaperLeNom")
        RecupererationMatiere.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(RecupererationMatiere)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        RecupererationMatiere.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RecupererationMatiere)
        self.statusbar.setObjectName("statusbar")
        RecupererationMatiere.setStatusBar(self.statusbar)
        self.retranslateUi(RecupererationMatiere)
        QtCore.QMetaObject.connectSlotsByName(RecupererationMatiere)

    def retranslateUi(self, RecupererationMatiere):
        _translate = QtCore.QCoreApplication.translate
        RecupererationMatiere.setWindowTitle(_translate("RecupererationMatiere", "Recupereration Matiere"))
        self.Icon.setText(_translate("RecupererationMatiere",
                                     "<html><head/><body><p><img src=\":/newPrefix/livre.png\"/></p></body></html>"))
        self.label.setText(_translate("RecupererationMatiere",
                                      "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Recupereration de tableau matiere</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("RecupererationMatiere", ".csv"))
        self.comboBox.setItemText(1, _translate("RecupererationMatiere", ".txt"))
        self.ButtonRecuperer.setText(_translate("RecupererationMatiere", "Recuperer"))
        self.TaperLeNom.setText(_translate("RecupererationMatiere",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Taper le nom du fichier</span></p></body></html>"))

    def SuccesssMsg(self):
        msg = QMessageBox()
        msg.setWindowTitle("Recupereration validée")
        msg.setText("Le tableau est récupéré")
        msg.setStandardButtons(QMessageBox.Ok)
        x = msg.exec_()

    def FailedMsg(self):
        msg = QMessageBox()
        msg.setWindowTitle("Recupereration echouée")
        msg.setText("Recupereration echouée !")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.setIcon(QMessageBox.Critical)
        msg.setDetailedText(
            "Impossible d'accéder au fichier. Essayez l'une des opérations suivantes :\n-Vérifiez que le dossier spécifié existe. \n-Vérifiez que le dossier contenant le fichier n'est pas en lecture seule.")
        x = msg.exec_()

    def Recuperer(self):
        NomFichier = self.NomFichier.text()
        type = self.comboBox.currentText()
        print(type)

        if (type == ".txt"):
            Mat.Matieres = RecupererTXT(NomFichier)
        else:
            Mat.Matieres = RecupererCSV(NomFichier)
        if (Mat.Matieres != False):
            self.SuccesssMsg()

        else:
            self.FailedMsg()


import icons_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))

    RecupererationMatiere = QtWidgets.QMainWindow()
    ui = Ui_RecupererationMatiere()
    ui.setupUi(RecupererationMatiere)
    RecupererationMatiere.show()
    sys.exit(app.exec_())