# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaperLeNumInscritET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Bulletin import Ui_Bulletin
import Etudiant as ET
import Note as NT

class Ui_SaisieNumInscritET(object):
    def openBulletin (self):
        self.window=QtWidgets.QMainWindow()
        self.ui= Ui_Bulletin()
        self.ui.setupUi(self.window,Numinscrit,"")
        self.window.show()
    

    def setupUi(self, SaisieNumInscritET):

        
        SaisieNumInscritET.setObjectName("SaisieNumInscritET")
        SaisieNumInscritET.resize(556, 444)
        self.centralwidget = QtWidgets.QWidget(SaisieNumInscritET)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.948, y2:0.936864, stop:0.522727 rgba(10, 204, 184, 250), stop:1 rgba(30, 169, 234)) \n"
"}")
        self.widget.setObjectName("widget")
        self.Numinscrit = QtWidgets.QLineEdit(self.widget)
        self.Numinscrit.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Numinscrit.setFont(font)
        self.Numinscrit.setObjectName("Numinscrit")
        self.pushButtonChercher = QtWidgets.QPushButton(self.widget)
        self.pushButtonChercher.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonChercher.setObjectName("pushButtonChercher")
        self.pushButtonChercher.clicked.connect(self.getInfos)
        
        self.Numinscrit_2 = QtWidgets.QLabel(self.widget)
        self.Numinscrit_2.setGeometry(QtCore.QRect(180, 140, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Numinscrit_2.setFont(font)
        self.Numinscrit_2.setObjectName("Numinscrit_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(30, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(130, 70, 261, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        self.infoinvalideInscrit = QtWidgets.QLabel(self.widget)
        self.infoinvalideInscrit.setGeometry(QtCore.QRect(170, 210, 251, 31))
        self.infoinvalideInscrit.setObjectName("infoinvalideInscrit")
        self.infoinvalideInscrit.setHidden(True)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 40, 361, 21))
        self.label.setObjectName("label")
        SaisieNumInscritET.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SaisieNumInscritET)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        SaisieNumInscritET.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SaisieNumInscritET)
        self.statusbar.setObjectName("statusbar")
        SaisieNumInscritET.setStatusBar(self.statusbar)

        self.retranslateUi(SaisieNumInscritET)
        QtCore.QMetaObject.connectSlotsByName(SaisieNumInscritET)

    def retranslateUi(self, SaisieNumInscritET):
        _translate = QtCore.QCoreApplication.translate
        SaisieNumInscritET.setWindowTitle(_translate("SaisieNumInscritET", "Recherche par numero d'inscription"))
        self.pushButtonChercher.setText(_translate("SaisieNumInscritET", "Chercher"))
        self.Numinscrit_2.setText(_translate("SaisieNumInscritET", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Numero d\'inscription</span></p></body></html>"))
        self.Icon.setText(_translate("SaisieNumInscritET", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("SaisieNumInscritET", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">L\'étudiant n\'existe pas</span></p></body></html>"))
        self.infoinvalideInscrit.setText(_translate("SaisieNumInscritET", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Numero d\'inscription invalide</span></p></body></html>"))
        self.label.setText(_translate("SaisieNumInscritET", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le numero d\'inscription de l\'étudiant</span></p></body></html>"))
    def getInfos(self):
        global Numinscrit
        Numinscrit=self.Numinscrit.text()
        T=[]
        for i in list(NT.Notes.keys()) :
            T.append( list (i)[0])
            
        if (ET.SaisieNumInscrit(Numinscrit)) and (Numinscrit in T):
            self.openBulletin()     
        elif not(ET.SaisieNumInscrit(Numinscrit)):
            self.infoinvalideInscrit.setHidden(False)
      
            self.Letudiantnexistepas.setHidden(True)
        elif not(Numinscrit  in NT.Notes.keys()):
            self.Letudiantnexistepas.setHidden(False)
           
            self.infoinvalideInscrit.setHidden(True)
        
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    SaisieNumInscritET = QtWidgets.QMainWindow()
    ui = Ui_SaisieNumInscritET()
    ui.setupUi(SaisieNumInscritET)
    SaisieNumInscritET.show()
    sys.exit(app.exec_())