# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SupEtudiantNumInscrit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Etudiant as ET
import Note as NT

class Ui_SupEtudiantNumInscrit(object):
    def setupUi(self, SupEtudiantNumInscrit):
        SupEtudiantNumInscrit.setObjectName("SupEtudiantNumInscrit")
        SupEtudiantNumInscrit.resize(540, 466)
        self.centralwidget = QtWidgets.QWidget(SupEtudiantNumInscrit)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 60, 461, 21))
        self.label.setObjectName("label")
        self.Numinscrit = QtWidgets.QLineEdit(self.widget)
        self.Numinscrit.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Numinscrit.setFont(font)
        self.Numinscrit.setObjectName("Numinscrit")
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widget)
        self.pushButtonSupprimer.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.pushButtonSupprimer.clicked.connect(self.getInfos) 
        self.Numinscrit_2 = QtWidgets.QLabel(self.widget)
        self.Numinscrit_2.setGeometry(QtCore.QRect(210, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Numinscrit_2.setFont(font)
        self.Numinscrit_2.setObjectName("Numinscrit_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(50, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Letudiantnexistepas = QtWidgets.QLabel(self.widget)
        self.Letudiantnexistepas.setGeometry(QtCore.QRect(180, 80, 261, 31))
        self.Letudiantnexistepas.setObjectName("Letudiantnexistepas")
        self.Letudiantnexistepas.setHidden(True)
        self.SuppressionErreur = QtWidgets.QLabel(self.widget)
        self.SuppressionErreur.setGeometry(QtCore.QRect(160, 260, 181, 101))
        self.SuppressionErreur.setObjectName("SuuppressionErreur")
        self.SuppressionErreur.setHidden(True)
        self.infoinvalide = QtWidgets.QLabel(self.widget)
        self.infoinvalide.setGeometry(QtCore.QRect(170, 210, 261, 31))
        self.infoinvalide.setObjectName("infoinvalide")
        self.infoinvalide.setHidden(True)
        SupEtudiantNumInscrit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SupEtudiantNumInscrit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")

        SupEtudiantNumInscrit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SupEtudiantNumInscrit)
        self.statusbar.setObjectName("statusbar")
        SupEtudiantNumInscrit.setStatusBar(self.statusbar)
        self.retranslateUi(SupEtudiantNumInscrit)
        QtCore.QMetaObject.connectSlotsByName(SupEtudiantNumInscrit)
        
    
    def retranslateUi(self, SupEtudiantNumInscrit):
        _translate = QtCore.QCoreApplication.translate
        SupEtudiantNumInscrit.setWindowTitle(_translate("SupEtudiantNumInscrit", "Supperession d'un étudiant"))
        self.pushButtonSupprimer.setText(_translate("SupEtudiantNumInscrit", "Supprimer"))
        self.Numinscrit_2.setText(_translate("SupEtudiantNumInscrit", "<html><head/><body><p><span style=\" color:#ffffff;\">Numero d\'inscription</span></p></body></html>"))
        self.Icon.setText(_translate("SupEtudiantNumInscrit", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.Letudiantnexistepas.setText(_translate("SupEtudiantNumInscrit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">L\'étudiant n\'existe pas</span></p></body></html>"))
        self.SuppressionErreur.setText(_translate("SupEtudiantNumInscrit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Suppression Invalide</span></p></body></html>"))
        self.infoinvalide.setText(_translate("SupEtudiantNumInscrit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Numero d\'inscription invalide</span></p></body></html>"))
        self.label.setText(_translate("SupEtudiantNumInscrit",
                                  "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le numero d'iscription de l'étudiant</span></p></body></html>"))


    def getInfos(self):
        Numinscrit=self.Numinscrit.text()
        T=[]
        for i in list(NT.Notes.keys()):

            if i[0]==Numinscrit:
                T.append(i)

        if (ET.SaisieNumInscrit(Numinscrit))and (Numinscrit in ET.Etudiants.keys()) :
            ET.Etudiants.pop(Numinscrit)
            for i in T:
                NT.Notes.pop(i)

            self.Letudiantnexistepas.setHidden(True)
            self.SuppressionErreur.setHidden(True)
            self.infoinvalide.setHidden(True)     
        elif not(ET.SaisieNumInscrit(Numinscrit)):
            self.infoinvalide.setHidden(False)
            self.SuppressionErreur.setHidden(False)
            self.Letudiantnexistepas.setHidden(True)
        elif not(Numinscrit  in ET.Etudiants.keys()):
            self.Letudiantnexistepas.setHidden(False)
            self.SuppressionErreur.setHidden(False)
            self.infoinvalide.setHidden(True)
        
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    SupEtudiantNumInscrit = QtWidgets.QMainWindow()
    ui = Ui_SupEtudiantNumInscrit()
    ui.setupUi(SupEtudiantNumInscrit)
    SupEtudiantNumInscrit.show()
    sys.exit(app.exec_())
