# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SupEtudiantNiveau.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Etudiant as ET
import Note as NT


def Keys (Niveau):
    Tab=[]
    for key in ET.Etudiants:
        if (ET.Etudiants[key][7]==Niveau):
            Tab.append(key)
    return Tab
        
class Ui_SupEtudiantNiveau(object):
    def setupUi(self, SupEtudiantNiveau):
        SupEtudiantNiveau.setObjectName("SupEtudiantNiveau")
        SupEtudiantNiveau.resize(540, 466)
        self.centralwidget = QtWidgets.QWidget(SupEtudiantNiveau)
        self.centralwidget.setObjectName("centralwidget")


        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 60, 461, 21))
        self.label.setObjectName("label")
        self.Niveau = QtWidgets.QLineEdit(self.widget)
        self.Niveau.setGeometry(QtCore.QRect(180, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau.setFont(font)
        self.Niveau.setObjectName("Niveau")
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widget)
        self.pushButtonSupprimer.setGeometry(QtCore.QRect(360, 300, 75, 23))
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.pushButtonSupprimer.clicked.connect(self.getInfos)
        self.Niveau_2 = QtWidgets.QLabel(self.widget)
        self.Niveau_2.setGeometry(QtCore.QRect(260, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau_2.setFont(font)
        self.Niveau_2.setObjectName("Niveau_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(50, 50, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Niveaunexistepas = QtWidgets.QLabel(self.widget)
        self.Niveaunexistepas.setGeometry(QtCore.QRect(180, 100, 261, 31))
        self.Niveaunexistepas.setObjectName("Niveaunexistepas")
        self.Niveaunexistepas.setHidden(True)
        self.SuppressionErreur = QtWidgets.QLabel(self.widget)
        self.SuppressionErreur.setGeometry(QtCore.QRect(160, 260, 181, 101))
        self.SuppressionErreur.setObjectName("SuppressionErreur")
        self.SuppressionErreur.setHidden(True)
        self.infoinvalide = QtWidgets.QLabel(self.widget)
        self.infoinvalide.setGeometry(QtCore.QRect(220, 210, 261, 31))
        self.infoinvalide.setObjectName("infoinvalide")
        self.infoinvalide.setHidden(True)
        SupEtudiantNiveau.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SupEtudiantNiveau)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        SupEtudiantNiveau.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SupEtudiantNiveau)
        self.statusbar.setObjectName("statusbar")
        SupEtudiantNiveau.setStatusBar(self.statusbar)

        self.retranslateUi(SupEtudiantNiveau)
        QtCore.QMetaObject.connectSlotsByName(SupEtudiantNiveau)

    def retranslateUi(self, SupEtudiantNiveau):
        _translate = QtCore.QCoreApplication.translate
        SupEtudiantNiveau.setWindowTitle(_translate("SupEtudiantNiveau", "Suppression d'un niveau d'étude"))
        self.pushButtonSupprimer.setText(_translate("SupEtudiantNiveau", "Supprimer"))
        self.Niveau_2.setText(_translate("SupEtudiantNiveau", "<html><head/><body><p><span style=\" color:#ffffff;\">Niveau</span></p></body></html>"))
        self.Icon.setText(_translate("SupEtudiantNiveau", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.Niveaunexistepas.setText(_translate("SupEtudiantNiveau", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Le Niveau n\'existe pas</span></p><p><br/></p></body></html>"))
        self.SuppressionErreur.setText(_translate("SupEtudiantNiveau", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Suppression Invalide</span></p></body></html>"))
        self.infoinvalide.setText(_translate("SupEtudiantNiveau", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Niveau invalide</span></p></body></html>"))

        self.label.setText(_translate("SupEtudiantNiveau",
                                  "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez le niveau que vous allez supprimer</span></p></body></html>"))

    def getInfos(self):
        Niveau=self.Niveau.text()
        T=[]

        if (ET.SaisieNiveauEtude(Niveau)) :
            if (ET.RechercheParNiveau(ET.Etudiants,Niveau)): 
                Tab=Keys(Niveau)
                T = []
                for i in list(NT.Notes.keys()):

                    if i[0] in Tab:
                        T.append(i)

                for j in Tab:
                    ET.Etudiants.pop(j)
                for i in T:
                    NT.Notes.pop(i)
                self.Niveaunexistepas.setHidden(True)
                self.SuppressionErreur.setHidden(True)
                self.infoinvalide.setHidden(True)     
            else :
                self.Niveaunexistepas.setHidden(False)
                self.SuppressionErreur.setHidden(False)
                self.infoinvalide.setHidden(True)
        else:
            self.infoinvalide.setHidden(False)
            self.SuppressionErreur.setHidden(False)
            self.Niveaunexistepas.setHidden(True)

import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    SupEtudiantNiveau = QtWidgets.QMainWindow()
    ui = Ui_SupEtudiantNiveau()
    ui.setupUi(SupEtudiantNiveau)
    SupEtudiantNiveau.show()
    sys.exit(app.exec_())

