# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SupNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Note as NT
import Etudiant as ET
import Matiere as Mat

class Ui_SupNote(object):
    def setupUi(self, SupNote):
        SupNote.setObjectName("SupNote")
        SupNote.resize(540, 466)
        self.centralwidget = QtWidgets.QWidget(SupNote)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 701, 771))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.NumInscrit = QtWidgets.QLineEdit(self.widget)
        self.NumInscrit.setGeometry(QtCore.QRect(180, 140, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit.setFont(font)
        self.NumInscrit.setObjectName("NumInscrit")
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widget)
        self.pushButtonSupprimer.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.pushButtonSupprimer.clicked.connect(self.getInfos) 
        self.NumInscrit_2 = QtWidgets.QLabel(self.widget)
        self.NumInscrit_2.setGeometry(QtCore.QRect(180, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumInscrit_2.setFont(font)
        self.NumInscrit_2.setObjectName("NumInscrit_2")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(50, 30, 101, 101))
        self.Icon.setObjectName("Icon")
        self.Noteinexistante = QtWidgets.QLabel(self.widget)
        self.Noteinexistante.setGeometry(QtCore.QRect(160, 50, 161, 31))
        self.Noteinexistante.setObjectName("Noteinexistante")
        self.Noteinexistante.setHidden(True)
        self.SuppressionErreur = QtWidgets.QLabel(self.widget)
        self.SuppressionErreur.setGeometry(QtCore.QRect(160, 310, 181, 51))
        self.SuppressionErreur.setObjectName("SuppressionErreur")
        self.SuppressionErreur.setHidden(True)
        self.infoinvalideNumInscrit = QtWidgets.QLabel(self.widget)
        self.infoinvalideNumInscrit.setGeometry(QtCore.QRect(170, 180, 251, 31))
        self.infoinvalideNumInscrit.setObjectName("infoinvalideNumInscrit")
        self.infoinvalideNumInscrit.setHidden(True)
        self.Code = QtWidgets.QLineEdit(self.widget)
        self.Code.setGeometry(QtCore.QRect(180, 240, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.Code_2 = QtWidgets.QLabel(self.widget)
        self.Code_2.setGeometry(QtCore.QRect(180, 210, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Code_2.setFont(font)
        self.Code_2.setObjectName("Code_2")
        self.infoinvalideCode = QtWidgets.QLabel(self.centralwidget)
        self.infoinvalideCode.setGeometry(QtCore.QRect(160, 270, 251, 31))
        self.infoinvalideCode.setObjectName("infoinvalideCode")
        self.infoinvalideCode.setHidden(True)
        SupNote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SupNote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        SupNote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SupNote)
        self.statusbar.setObjectName("statusbar")
        SupNote.setStatusBar(self.statusbar)

        self.retranslateUi(SupNote)
        QtCore.QMetaObject.connectSlotsByName(SupNote)

    def retranslateUi(self, SupNote):
        _translate = QtCore.QCoreApplication.translate
        SupNote.setWindowTitle(_translate("SupNote", "Supression d'une note"))
        self.pushButtonSupprimer.setText(_translate("SupNote", "Supprimer"))
        self.NumInscrit_2.setText(_translate("SupNote", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Numero d\'inscription</span></p></body></html>"))
        self.Icon.setText(_translate("SupNote", "<html><head/><body><p><img src=\":/newPrefix/183338.png\"/></p></body></html>"))
        self.Noteinexistante.setText(_translate("SupNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Note inexistante</span></p></body></html>"))
        self.SuppressionErreur.setText(_translate("SupNote", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Suppression Invalide</span></p></body></html>"))
        self.infoinvalideNumInscrit.setText(_translate("SupNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Numero d\'inscription invalide</span></p></body></html>"))
        self.Code_2.setText(_translate("SupNote", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Code</span></p></body></html>"))
        self.infoinvalideCode.setText(_translate("SupNote", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Code invalide</span></p></body></html>"))
    
    def getInfos(self):
        NumInscrit=self.NumInscrit.text()
        Code=self.Code.text()
        
        if (ET.SaisieNumInscrit(NumInscrit))and (Mat.SaisieCode(Code))and ((NumInscrit, Code) in NT.Notes ) :
            NT.Notes.pop((NumInscrit, Code))
            self.Noteinexistante.setHidden(True)
            self.SuppressionErreur.setHidden(True)
            self.infoinvalideNumInscrit.setHidden(True)    
            self.infoinvalideCode.setHidden(True)    
        if not(ET.SaisieNumInscrit(NumInscrit)):
            self.infoinvalideNumInscrit.setHidden(False)
            self.SuppressionErreur.setHidden(False)
        else:
            self.infoinvalideNumInscrit.setHidden(True)  
        if not(Mat.SaisieCode(Code)):
            self.infoinvalideCode.setHidden(False)
            self.SuppressionErreur.setHidden(False)
        else:
            self.infoinvalideCode.setHidden(True) 
        
        if not((NumInscrit, Code) in NT.Notes ):
            self.Noteinexistante.setHidden(False)
            self.SuppressionErreur.setHidden(False)
        else :
            self.Noteinexistante.setHidden(True)
        




import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))

    SupNote = QtWidgets.QMainWindow()
    ui = Ui_SupNote()
    ui.setupUi(SupNote)
    SupNote.show()
    sys.exit(app.exec_())
