# -*- coding: utf-8 -*-

# SuppressionSection_Niveau implementation generated from reading ui file 'SuppSectionNivET.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Etudiant as ET
import Note as NT
def Keys (Section,Niveau):
    Tab=[]
    for key in ET.Etudiants:
        if (ET.Etudiants[key][7]==Niveau) and (ET.Etudiants[key][6]==Section) :
            Tab.append(key)
    return Tab

class Ui_SuppressionSection_Niveau(object):
    def setupUi(self, SuppressionSection_Niveau):
        SuppressionSection_Niveau.setObjectName("SuppressionSection_Niveau")
        SuppressionSection_Niveau.resize(643, 470)
        self.widget = QtWidgets.QWidget(SuppressionSection_Niveau)
        self.widget.setGeometry(QtCore.QRect(-20, 0, 841, 481))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.893, y2:0, stop:0 rgba(92, 37, 141, 255), stop:1 rgba(67, 137, 162, 255))\n"
" }")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(180, 40, 361, 21))
        self.label.setObjectName("label")


        self.Section = QtWidgets.QLineEdit(self.widget)
        self.Section.setGeometry(QtCore.QRect(220, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section.setFont(font)
        self.Section.setObjectName("Section")
        self.Section_2 = QtWidgets.QLabel(self.widget)
        self.Section_2.setGeometry(QtCore.QRect(300, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Section_2.setFont(font)
        self.Section_2.setObjectName("Section_2")
        self.Etudiantinexistant = QtWidgets.QLabel(self.widget)
        self.Etudiantinexistant.setGeometry(QtCore.QRect(170, 60, 371, 30))
        self.Etudiantinexistant.setObjectName("Etudiantinexistant")
        self.Icon = QtWidgets.QLabel(self.widget)
        self.Icon.setGeometry(QtCore.QRect(50, 40, 101, 101))
        self.Icon.setObjectName("Icon")
        self.infoinvalide = QtWidgets.QLabel(self.widget)
        self.infoinvalide.setGeometry(QtCore.QRect(470, 150, 261, 31))
        self.infoinvalide.setObjectName("infoinvalide")
        self.SuppressionErreur = QtWidgets.QLabel(self.widget)
        self.SuppressionErreur.setGeometry(QtCore.QRect(320, 310, 181, 101))
        self.SuppressionErreur.setObjectName("SuppressionErreur")
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widget)
        self.pushButtonSupprimer.setGeometry(QtCore.QRect(520, 350, 75, 23))
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.pushButtonSupprimer.clicked.connect(self.getInfos)
        self.Niveau = QtWidgets.QLineEdit(self.widget)
        self.Niveau.setGeometry(QtCore.QRect(220, 250, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau.setFont(font)
        self.Niveau.setObjectName("Niveau")
        self.infoinvalide_2 = QtWidgets.QLabel(self.widget)
        self.infoinvalide_2.setGeometry(QtCore.QRect(470, 250, 261, 31))
        self.infoinvalide_2.setObjectName("infoinvalide_2")
        self.infoinvalide_2.setHidden(True)
        self.Niveau_2 = QtWidgets.QLabel(self.widget)
        self.Niveau_2.setGeometry(QtCore.QRect(300, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Niveau_2.setFont(font)
        self.Niveau_2.setObjectName("Niveau_2")
        self.Etudiantinexistant.setHidden(True)
        self.SuppressionErreur.setHidden(True)
        self.infoinvalide.setHidden(True)  
        self.retranslateUi(SuppressionSection_Niveau)
        QtCore.QMetaObject.connectSlotsByName(SuppressionSection_Niveau)

    def retranslateUi(self, SuppressionSection_Niveau):
        _translate = QtCore.QCoreApplication.translate
        SuppressionSection_Niveau.setWindowTitle(_translate("SuppressionSection_Niveau", "Suppression des étudiants d'une section et un niveau"))
        self.Section_2.setText(_translate("SuppressionSection_Niveau", "<html><head/><body><p><span style=\" color:#ffffff;\">Section</span></p></body></html>"))
        self.Etudiantinexistant.setText(_translate("SuppressionSection_Niveau", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ff0000;\">Étudiant inexistant</span></p></body></html>"))
        self.Icon.setText(_translate("SuppressionSection_Niveau", "<html><head/><body><p><img src=\":/newPrefix/etudiant.png\"/></p></body></html>"))
        self.infoinvalide.setText(_translate("SuppressionSection_Niveau", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Section invalide</span></p></body></html>"))
        self.SuppressionErreur.setText(_translate("SuppressionSection_Niveau", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Suppression Invalide</span></p></body></html>"))
        self.pushButtonSupprimer.setText(_translate("SuppressionSection_Niveau", "Supprimer"))
        self.infoinvalide_2.setText(_translate("SuppressionSection_Niveau", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Niveau invalide</span></p></body></html>"))
        self.Niveau_2.setText(_translate("SuppressionSection_Niveau", "<html><head/><body><p><span style=\" color:#ffffff;\">Niveau</span></p></body></html>"))
        self.label.setText(_translate("SuppressionSection_Niveau",
                                  "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Tapez la section et le niveau de l\'étudiant</span></p></body></html>"))

    def getInfos(self):
        Section=self.Section.text()
        Niveau=self.Niveau.text()
        self.infoinvalide.setHidden(True)
        self.infoinvalide_2.setHidden(True)        
        if (not ET.SaisieSection(Section)):
            self.infoinvalide.setHidden(False)
        if (not ET.SaisieNiveauEtude(Niveau)):
            self.infoinvalide_2.setHidden(False)    
        
        
        
        if ((ET.SaisieSection(Section))and ET.SaisieNiveauEtude(Niveau)):
            if (ET.RechercheParSection_Niveau(ET.Etudiants,Section,Niveau)): 
                Tab=Keys(Section,Niveau)
                T = []
                for i in list(NT.Notes.keys()):

                    if i[0] in Tab:
                        T.append(i)
                for j in Tab:
                    ET.Etudiants.pop(j)
                for i in T:
                    NT.Notes.pop(i)

                self.Etudiantinexistant.setHidden(True)
                self.SuppressionErreur.setHidden(True)
                self.infoinvalide.setHidden(True)
                self.infoinvalide_2.setHidden(True)
            else :
                self.infoinvalide.setHidden(True)
                self.SuppressionErreur.setHidden(False)
                self.Etudiantinexistant.setHidden(False)
                self.infoinvalide_2.setHidden(True)
        else:
            self.Etudiantinexistant.setHidden(True)
            self.SuppressionErreur.setHidden(False)



import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('ISIMM_LOGO.png'))
    SuppressionSection_Niveau = QtWidgets.QWidget()
    ui = Ui_SuppressionSection_Niveau()
    ui.setupUi(SuppressionSection_Niveau)
    SuppressionSection_Niveau.show()
    sys.exit(app.exec_())
